import React from 'react';
import ModalLarge from '../../../components/common/ModalLarge';
import FilledButton from '../../../components/common/FilledButton';
import LinedButton from '../../../components/common/LinedButton';
import BuildWarningIcon from '../../../assets/icons/build_warning_icon.svg?react';
import ImportErdPreview from '../../../assets/images/import_erd_preview.svg?react';

type ImportResultType = 'success' | 'error';

interface ImportResultModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirm?: () => void;
  type: ImportResultType;
  correctedSql?: string;
  changeSummary?: string[];
}

const DEFAULT_CHANGE_SUMMARY = [
  'snapshots 테이블의 기본 키 타입을 BIGINT IDENTITY로 자동 변환했습니다.',
  'schema 컬럼을 JSONB 타입으로 지정하여 JSON 저장을 지원합니다.',
  'created_at 컬럼에 기본값 now()를 추가하여 생성 시간을 자동 저장합니다.',
];

const ImportResultModal: React.FC<ImportResultModalProps> = ({
  isOpen,
  onClose,
  onConfirm,
  type,
  correctedSql,
  changeSummary,
}) => {
  const summaryItems =
    changeSummary && changeSummary.length > 0
      ? changeSummary
      : DEFAULT_CHANGE_SUMMARY;

  const footer = (
    <div className="mt-6 flex justify-end gap-3">
      <LinedButton label="취소" onClick={onClose} size="px-5 py-2 text-sm" />
      <FilledButton
        label="확인"
        onClick={onConfirm ?? onClose}
        size="px-5 py-2 text-sm"
      />
    </div>
  );

  if (type === 'success') {
    return (
      <ModalLarge isOpen={isOpen} onClose={onClose} title="Import 결과">
        <div className="flex flex-col gap-4">
          <div className="rounded-xl border border-blue/20 bg-blue/10 px-5 py-4">
            <p className="text-lg font-semibold text-my-black">
              워크스페이스에 ERD를 반영했습니다.
            </p>
            <p className="mt-1 text-sm text-my-black/70">
              생성된 테이블을 바로 확인하고 수정할 수 있습니다.
            </p>
          </div>
          {footer}
        </div>
      </ModalLarge>
    );
  }

  const sqlText =
    correctedSql ??
    `CREATE TABLE "snapshots" (
  "snapshot_key" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_key" INTEGER NOT NULL,
  "created_by" INTEGER NOT NULL,
  "name" VARCHAR(500) NOT NULL DEFAULT '',
  "schema" JSONB NOT NULL DEFAULT '{}',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);`;

  return (
    <ModalLarge isOpen={isOpen} onClose={onClose} title="Import">
      <div className="flex flex-col gap-6">
        <div className="flex items-start gap-3 rounded-xl border border-warning/20 bg-warning/10 px-5 py-4">
          <BuildWarningIcon className="h-6 w-6 text-warning" />
          <div>
            <p className="text-lg font-semibold text-my-black">
              AI 구문 검사를 통해 오류가 검출되었습니다.
            </p>
            <p className="mt-1 text-sm text-my-black/70">
              아래 제안된 수정 사항을 확인하고 ERD에 반영해 주세요.
            </p>
          </div>
        </div>

        <div className="flex flex-col gap-4">
          <h4 className="text-base font-semibold text-my-black">수정된 부분</h4>
          <ul className="flex flex-col gap-2 rounded-xl border border-my-border bg-my-white px-5 py-4 text-sm text-my-black/80">
            {summaryItems.map((item) => (
              <li key={item} className="flex gap-3">
                <span className="mt-[6px] inline-block h-2 w-2 rounded-full bg-blue" />
                <span className="leading-6">{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="flex flex-col gap-3">
          <h4 className="text-base font-semibold text-my-black">
            수정된 ERD 미리보기
          </h4>
          <div className="rounded-2xl border border-my-border bg-my-white p-4">
            <ImportErdPreview className="h-auto w-full" />
          </div>
        </div>

        <div className="flex flex-col gap-3">
          <h4 className="text-base font-semibold text-my-black">제안된 DDL</h4>
          <textarea
            readOnly
            value={sqlText}
            className="h-52 w-full resize-none rounded-2xl border border-my-border bg-gray-50 p-4 font-mono text-sm text-my-black focus:outline-none"
          />
        </div>

        {footer}
      </div>
    </ModalLarge>
  );
};

export default ImportResultModal;
