-- =====================================================
-- WARN: sql 원본이지만 프로젝트의 스키마는 flyway (db.migration)에서 관리됩니다.
-- 01_ddl.sql
-- Table Definitions (DDL)
-- Organized in hierarchical dependency order
-- =====================================================

-- =====================================================
-- CORE ENTITIES
-- =====================================================f

-- Users (root entity)
CREATE TABLE IF NOT EXISTS users (
    user_key    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255) NOT NULL,
    nickname    VARCHAR(10) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,
    PRIMARY KEY (user_key)
);

-- User social accounts
CREATE TABLE IF NOT EXISTS user_social_accounts (
    social_account_key  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key            INTEGER NOT NULL,
    provider            VARCHAR(50) NOT NULL CHECK (provider IN ('GOOGLE','GITHUB','SSAFY')),
    oauth_user_id       VARCHAR(255) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (social_account_key),
    UNIQUE (provider, oauth_user_id)
);

-- =====================================================
-- TEAM HIERARCHY
-- =====================================================

-- Teams
CREATE TABLE IF NOT EXISTS teams (
    team_key    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owned_by    INTEGER NOT NULL,
    name        VARCHAR(25) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,
    PRIMARY KEY (team_key)
);

-- User-Team relations
CREATE TABLE IF NOT EXISTS user_team_relations (
    user_team_relation_key  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key                INTEGER NOT NULL,
    team_key                INTEGER NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_team_relation_key),
    UNIQUE (user_key, team_key)
);

-- User team history
CREATE TABLE IF NOT EXISTS user_team_history (
    user_team_history_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_key               INTEGER NOT NULL,
    actor_key              BIGINT NOT NULL,
    target_key             BIGINT,
    email                  VARCHAR(255),
    action_type            VARCHAR(50) NOT NULL CHECK (action_type IN ('INVITE_SENT', 'INVITE_ACCEPTED', 'INVITE_REJECTED', 'INVITE_CANCELED', 'INVITE_EXPIRED', 'MEMBER_JOINED', 'MEMBER_EXITED', 'MEMBER_EXPULSION', 'MEMBER_WITHDRAWAL', 'MEMBER_REJOIN', 'OWNER_CHANGED')),
    reason                 VARCHAR(255) DEFAULT '',
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_team_history_key)
);

-- =====================================================
-- PROJECT HIERARCHY
-- =====================================================

-- Projects
CREATE TABLE IF NOT EXISTS projects (
    project_key       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_key          INTEGER NOT NULL,
    name              VARCHAR(25) NOT NULL,
    description       VARCHAR(1000) NOT NULL DEFAULT '',
    image_url         VARCHAR(3000),
    last_activity_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ,
    PRIMARY KEY (project_key)
);

-- Project member relations
CREATE TABLE IF NOT EXISTS project_member_relations (
    project_member_relations_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key         BIGINT NOT NULL,
    member_key          INTEGER NOT NULL,
    role                project_member_role_type NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (project_member_relations_key),
    UNIQUE (project_key, member_key)
);

-- Project member history
CREATE TABLE IF NOT EXISTS project_member_history (
    project_member_history_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key                 BIGINT NOT NULL,
    actor_key                   INTEGER NOT NULL,
    target_key                  INTEGER NOT NULL,
    action_type                 VARCHAR(50) NOT NULL CHECK (action_type IN ('ADD', 'EXPULSION', 'EXIT', 'WITHDRAWAL', 'REJOIN', 'ROLE_CHANGED')),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (project_member_history_key)
);

-- =====================================================
-- ERD STRUCTURE (Tables, Columns, Relations)
-- =====================================================

-- ERD Tables
CREATE TABLE IF NOT EXISTS erd_tables (
    table_key      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key    BIGINT NOT NULL,
    logical_name   VARCHAR(255) NOT NULL DEFAULT '',
    physical_name  VARCHAR(255) NOT NULL DEFAULT '',
    x_position     NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (x_position >= 0),
    y_position     NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (y_position >= 0),
    color_hex      VARCHAR(6) CHECK (color_hex ~ '^[0-9A-Fa-f]{6}$'),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,
    PRIMARY KEY (table_key)
);

-- ERD Columns
CREATE TABLE IF NOT EXISTS erd_columns (
    column_key      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_key       BIGINT NOT NULL,
    logical_name    VARCHAR(255) NOT NULL,
    physical_name   VARCHAR(255) NOT NULL,
    data_type       VARCHAR(255) NOT NULL,
    data_detail     TEXT[],
    is_nullable     BOOLEAN NOT NULL DEFAULT true,
    is_primary_key  BOOLEAN NOT NULL DEFAULT false,
    is_foreign_key  BOOLEAN NOT NULL DEFAULT false,
    is_unique       BOOLEAN NOT NULL DEFAULT false,
    is_incremental  BOOLEAN NOT NULL DEFAULT false,
    default_value   VARCHAR(255),
    comment         VARCHAR(500),
    column_order    INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    PRIMARY KEY (column_key)
);

-- ERD Relations
CREATE TABLE IF NOT EXISTS erd_relations (
    relation_key      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key       BIGINT NOT NULL,
    from_table_key    BIGINT NOT NULL,
    from_column_key   BIGINT,
    to_table_key      BIGINT NOT NULL,
    to_column_key     BIGINT,
    relation_type     relation_type NOT NULL,
    constraint_name   VARCHAR(255) DEFAULT '',
    on_delete_action  referential_action_type NOT NULL DEFAULT 'NO_ACTION',
    on_update_action  referential_action_type NOT NULL DEFAULT 'NO_ACTION',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ,
    PRIMARY KEY (relation_key)
);

-- =====================================================
-- COLLABORATION FEATURES
-- =====================================================

-- Comments
CREATE TABLE IF NOT EXISTS comments (
    comment_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key     INTEGER NOT NULL,
    table_key    BIGINT,
    project_key  BIGINT NOT NULL,
    content      VARCHAR(1000) NOT NULL DEFAULT '',
    color_hex    VARCHAR(6),
    x_position   NUMERIC(10,2),
    y_position   NUMERIC(10,2),
    is_resolved  BOOLEAN NOT NULL DEFAULT false,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    PRIMARY KEY (comment_key)
);

-- Replies
CREATE TABLE IF NOT EXISTS replies (
    reply_key    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_key  BIGINT NOT NULL,
    user_key     INTEGER NOT NULL,
    content      VARCHAR(1000) NOT NULL DEFAULT '',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    PRIMARY KEY (reply_key)
);

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
    notification_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key          INTEGER NOT NULL,
    type              VARCHAR(50) NOT NULL,
    content           VARCHAR(50),
    target            BIGINT,
    read_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (notification_key)
);

-- =====================================================
-- ASYNC JOB TRACKING
-- =====================================================

-- Async jobs (Kafka 비동기 작업 추적)
CREATE TABLE IF NOT EXISTS async_jobs (
    job_id           VARCHAR(26) NOT NULL,
    job_type         VARCHAR(50) NOT NULL,
    user_key         INTEGER NOT NULL,
    reference_key    BIGINT,
    status           VARCHAR(20) NOT NULL,
    error_message    TEXT,
    completed_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (job_id)
);

-- =====================================================
-- VERSION CONTROL & HISTORY
-- =====================================================

-- Versions
CREATE TABLE IF NOT EXISTS versions (
    version_key                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key                 BIGINT NOT NULL,
    job_id                      VARCHAR(26),
    name                        VARCHAR(255) NOT NULL DEFAULT '',
    schema_data                 JSONB NOT NULL,
    description                 VARCHAR(1000) NOT NULL DEFAULT '',
    design_verification_status  design_verification_status_type NOT NULL DEFAULT 'QUEUED',
    verification_result         JSONB,
    is_public                   BOOLEAN NOT NULL DEFAULT false,
    vector                      vector(1536),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at                  TIMESTAMPTZ,
    PRIMARY KEY (version_key),
    CONSTRAINT fk_versions_async_job FOREIGN KEY (job_id) REFERENCES async_jobs(job_id)
);

-- Snapshots
CREATE TABLE IF NOT EXISTS snapshots (
    snapshot_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key   BIGINT NOT NULL,
    created_by    INTEGER NOT NULL,
    name          VARCHAR(500) NOT NULL DEFAULT '',
    schema_data   JSONB NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ,
    PRIMARY KEY (snapshot_key),
    UNIQUE (project_key, name)
);

-- Edit history
CREATE TABLE IF NOT EXISTS edit_history (
    edit_history_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key          INTEGER NOT NULL,
    project_key       BIGINT NOT NULL,
    target_key        BIGINT,
    target_type       VARCHAR(50) CHECK (target_type IN ('TABLE', 'COLUMN', 'RELATION')),
    action_type       VARCHAR(50) NOT NULL CHECK (action_type IN ('ADD', 'UPDATE', 'RENAME', 'DELETE')),
    delta             JSONB,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    before_state      JSONB,
    after_state       JSONB,
    PRIMARY KEY (edit_history_key)
);

-- =====================================================
-- CODE GENERATION & DATA MODELS
-- =====================================================

-- Data models
CREATE TABLE IF NOT EXISTS data_models (
    model_key        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key      BIGINT NOT NULL,
    name             VARCHAR(500) NOT NULL,
    type             VARCHAR(50) NOT NULL CHECK (type IN ('ENTITY', 'DTO_REQUEST', 'DTO_RESPONSE')),
    source_table_key BIGINT,
    last_synced_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ,
    PRIMARY KEY (model_key),
    UNIQUE (project_key, name)
);

-- Data Model - ERD Column relations
CREATE TABLE IF NOT EXISTS data_model_erd_column_relations (
    model_column_relation_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    column_key                 BIGINT NOT NULL,
    model_key                  BIGINT NOT NULL,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
--     deleted_at  TIMESTAMPTZ,
    PRIMARY KEY (model_column_relation_key),
    UNIQUE (column_key, model_key)
);

-- Mock data
CREATE TABLE IF NOT EXISTS mock_data (
    mock_data_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_id         VARCHAR(26) NOT NULL,
    version_key    BIGINT NOT NULL,
    file_name      VARCHAR(500),
    file_path      TEXT,
    row_counts     SMALLINT NOT NULL CHECK (row_counts > 0),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,
    PRIMARY KEY (mock_data_key),
    CONSTRAINT fk_mock_data_async_job FOREIGN KEY (job_id) REFERENCES async_jobs(job_id)
);


-- =====================================================
-- SCHEDULER & BATCH
-- =====================================================

-- Scheduler execution logs
CREATE TABLE IF NOT EXISTS scheduler_execution_logs (
    log_key           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_name          VARCHAR(100) NOT NULL,
    status            VARCHAR(20) NOT NULL CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    started_at        TIMESTAMPTZ NOT NULL,
    completed_at      TIMESTAMPTZ,
    execution_time_ms BIGINT,
    deleted_count     INTEGER DEFAULT 0,
    error_message     TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (log_key)
);
