export const theme = {
  myBlue: 'blue',
  myLightBlue: 'light-blue',
  myBlack: 'my-black',
  myWhite: 'my-white',
  myBorder: 'my-border',
  aiChat: 'ai-chat',
  warning: 'warning',
  success: 'success',
  user2: 'user2',
  user3: 'user3',
  user4: 'user4',
  user5: 'user5',
  user6: 'user6',
  user7: 'user7',
  user8: 'user8',
  key: 'key',
  custom: 'custom',
  requestDto: 'requestdto',
  responseDto: 'responsedto',
  entity: 'entity',
  loginLeft: 'loginleft',
  fontSize: {},
};
