-- =====================================================
-- ERD Consultation Chatbot
-- consultation_messages 테이블 생성
-- =====================================================

-- Enum Type for Message Role
CREATE TYPE consultation_message_role_type AS ENUM ('USER', 'ASSISTANT');

-- Consultation Messages Table
CREATE TABLE IF NOT EXISTS consultation_messages (
    message_key             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key             BIGINT NOT NULL,
    role                    consultation_message_role_type NOT NULL,
    message                 TEXT NOT NULL,

    -- AI 응답인 경우만 사용되는 컬럼들
    schema_modifications    JSONB,
    confidence              REAL,
    agents_used             JSONB,
    warnings                JSONB,

    -- 스키마 스냅샷 (선택적)
    schema_snapshot         JSONB,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (message_key)
);

-- Indexes
CREATE INDEX idx_consultation_messages_project_created
    ON consultation_messages(project_key, created_at ASC);

CREATE INDEX idx_consultation_messages_role
    ON consultation_messages(project_key, role);

-- Foreign Key
ALTER TABLE consultation_messages
    ADD CONSTRAINT fk_consultation_messages_project
    FOREIGN KEY (project_key)
    REFERENCES projects(project_key)
    ON DELETE CASCADE;

-- Comments
COMMENT ON TABLE consultation_messages IS 'ERD 상담 챗봇 대화 내역';
COMMENT ON COLUMN consultation_messages.message_key IS '메시지 고유 키';
COMMENT ON COLUMN consultation_messages.project_key IS '프로젝트 외래 키';
COMMENT ON COLUMN consultation_messages.role IS '메시지 역할 (USER: 사용자 질문, ASSISTANT: AI 응답)';
COMMENT ON COLUMN consultation_messages.message IS '메시지 내용';
COMMENT ON COLUMN consultation_messages.schema_modifications IS 'AI 응답 시 적용 가능한 스키마 수정사항 (JSON 배열)';
COMMENT ON COLUMN consultation_messages.confidence IS 'AI 응답의 확신도 (0.0 ~ 1.0)';
COMMENT ON COLUMN consultation_messages.agents_used IS '사용된 Agent 목록 (JSON 배열)';
COMMENT ON COLUMN consultation_messages.warnings IS '경고 사항 (JSON 배열)';
COMMENT ON COLUMN consultation_messages.schema_snapshot IS '요청 시점의 스키마 스냅샷 (재현용)';
