-- =====================================================
-- 00_init.sql
-- PostgreSQL Extensions and Custom Types
-- =====================================================

-- Set timezone to UTC for consistency across all environments
SET TIMEZONE='UTC';
ALTER DATABASE yaldi SET TIMEZONE TO 'UTC';

-- Extensions
CREATE EXTENSION IF NOT EXISTS vector;

-- ENUM Types
CREATE TYPE design_verification_status_type AS ENUM ('QUEUED', 'RUNNING', 'SUCCESS', 'WARNING', 'FAILED', 'CANCELED');
CREATE TYPE relation_type AS ENUM ('OPTIONAL_ONE_TO_ONE', 'STRICT_ONE_TO_ONE', 'OPTIONAL_ONE_TO_MANY', 'STRICT_ONE_TO_MANY');
CREATE TYPE referential_action_type AS ENUM ('CASCADE', 'SET NULL', 'SET DEFAULT', 'RESTRICT', 'NO ACTION');
CREATE TYPE project_member_role_type AS ENUM ('OWNER', 'EDITOR', 'ADMIN');
-- =====================================================
-- 01_ddl.sql
-- Table Definitions (DDL)
-- Organized in hierarchical dependency order
-- =====================================================

-- =====================================================
-- CORE ENTITIES
-- =====================================================f

-- Users (root entity)
CREATE TABLE IF NOT EXISTS users (
    user_key    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255) NOT NULL,
    nickname    VARCHAR(10) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,
    PRIMARY KEY (user_key)
);

-- User social accounts
CREATE TABLE IF NOT EXISTS user_social_accounts (
    social_account_key  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key            INTEGER NOT NULL,
    provider            VARCHAR(50) NOT NULL CHECK (provider IN ('GOOGLE','GITHUB','SSAFY')),
    oauth_user_id       VARCHAR(255) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (social_account_key),
    UNIQUE (provider, oauth_user_id)
);

-- =====================================================
-- TEAM HIERARCHY
-- =====================================================

-- Teams
CREATE TABLE IF NOT EXISTS teams (
    team_key    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owned_by    INTEGER NOT NULL,
    name        VARCHAR(25) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,
    PRIMARY KEY (team_key)
);

-- User-Team relations
CREATE TABLE IF NOT EXISTS user_team_relations (
    user_team_relation_key  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key                INTEGER NOT NULL,
    team_key                INTEGER NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_team_relation_key),
    UNIQUE (user_key, team_key)
);

-- User team history
CREATE TABLE IF NOT EXISTS user_team_history (
    user_team_history_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_key               INTEGER NOT NULL,
    actor_key              BIGINT NOT NULL,
    target_key             BIGINT,
    email                  VARCHAR(255),
    action_type            VARCHAR(50) NOT NULL CHECK (action_type IN ('INVITE_SENT', 'INVITE_ACCEPTED', 'INVITE_REJECTED', 'INVITE_CANCELED', 'INVITE_EXPIRED', 'MEMBER_JOINED', 'MEMBER_EXITED', 'MEMBER_EXPULSION', 'MEMBER_WITHDRAWAL', 'MEMBER_REJOIN', 'OWNER_CHANGED')),
    reason                 VARCHAR(255) DEFAULT '',
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_team_history_key)
);

-- =====================================================
-- PROJECT HIERARCHY
-- =====================================================

-- Projects
CREATE TABLE IF NOT EXISTS projects (
    project_key       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_key          INTEGER NOT NULL,
    name              VARCHAR(25) NOT NULL,
    description       VARCHAR(1000) NOT NULL DEFAULT '',
    image_url         VARCHAR(10000),
    last_activity_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ,
    PRIMARY KEY (project_key)
);

-- Project member relations
CREATE TABLE IF NOT EXISTS project_member_relations (
    project_member_relations_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key         BIGINT NOT NULL,
    member_key          INTEGER NOT NULL,
    role                project_member_role_type NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (project_member_relations_key),
    UNIQUE (project_key, member_key)
);

-- Project member history
CREATE TABLE IF NOT EXISTS project_member_history (
    project_member_history_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key                 BIGINT NOT NULL,
    actor_key                   INTEGER NOT NULL,
    target_key                  INTEGER NOT NULL,
    action_type                 VARCHAR(50) NOT NULL CHECK (action_type IN ('ADD', 'EXPULSION', 'EXIT', 'WITHDRAWAL', 'REJOIN', 'ROLE_CHANGED')),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (project_member_history_key)
);

-- =====================================================
-- ERD STRUCTURE (Tables, Columns, Relations)
-- =====================================================

-- ERD Tables
CREATE TABLE IF NOT EXISTS erd_tables (
    table_key      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key    BIGINT NOT NULL,
    logical_name   VARCHAR(255) NOT NULL DEFAULT '',
    physical_name  VARCHAR(255) NOT NULL DEFAULT '',
    x_position     NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (x_position >= 0),
    y_position     NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (y_position >= 0),
    color_hex      VARCHAR(6) CHECK (color_hex ~ '^[0-9A-Fa-f]{6}$'),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,
    PRIMARY KEY (table_key)
);

-- ERD Columns
CREATE TABLE IF NOT EXISTS erd_columns (
    column_key      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_key       BIGINT NOT NULL,
    logical_name    VARCHAR(255) NOT NULL,
    physical_name   VARCHAR(255) NOT NULL,
    data_type       VARCHAR(255) NOT NULL,
    data_detail     TEXT[],
    is_nullable     BOOLEAN NOT NULL DEFAULT true,
    is_primary_key  BOOLEAN NOT NULL DEFAULT false,
    is_foreign_key  BOOLEAN NOT NULL DEFAULT false,
    is_unique       BOOLEAN NOT NULL DEFAULT false,
    is_incremental  BOOLEAN NOT NULL DEFAULT false,
    default_value   VARCHAR(255),
    comment         VARCHAR(500),
    column_order    INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    PRIMARY KEY (column_key)
);

-- ERD Relations
CREATE TABLE IF NOT EXISTS erd_relations (
    relation_key      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key       BIGINT NOT NULL,
    from_table_key    BIGINT NOT NULL,
    from_column_key   BIGINT,
    to_table_key      BIGINT NOT NULL,
    to_column_key     BIGINT,
    relation_type     relation_type NOT NULL,
    constraint_name   VARCHAR(255) DEFAULT '',
    on_delete_action  referential_action_type NOT NULL DEFAULT 'NO ACTION',
    on_update_action  referential_action_type NOT NULL DEFAULT 'NO ACTION',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ,
    PRIMARY KEY (relation_key)
);

-- =====================================================
-- COLLABORATION FEATURES
-- =====================================================

-- Comments
CREATE TABLE IF NOT EXISTS comments (
    comment_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key     INTEGER NOT NULL,
    table_key    BIGINT,
    project_key  BIGINT NOT NULL,
    content      VARCHAR(1000) NOT NULL DEFAULT '',
    color_hex    VARCHAR(6),
    x_position   NUMERIC(10,2),
    y_position   NUMERIC(10,2),
    is_resolved  BOOLEAN NOT NULL DEFAULT false,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    PRIMARY KEY (comment_key)
);

-- Replies
CREATE TABLE IF NOT EXISTS replies (
    reply_key    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_key  BIGINT NOT NULL,
    user_key     INTEGER NOT NULL,
    content      VARCHAR(1000) NOT NULL DEFAULT '',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    PRIMARY KEY (reply_key)
);

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
    notification_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key          INTEGER NOT NULL,
    type              VARCHAR(50) NOT NULL,
    content           VARCHAR(50),
    target            BIGINT,
    read_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (notification_key)
);

-- =====================================================
-- ASYNC JOB TRACKING
-- =====================================================

-- Async jobs (Kafka 비동기 작업 추적)
CREATE TABLE IF NOT EXISTS async_jobs (
    job_id           VARCHAR(26) NOT NULL,
    job_type         VARCHAR(50) NOT NULL,
    user_key         INTEGER NOT NULL,
    reference_key    BIGINT,
    status           VARCHAR(20) NOT NULL,
    error_message    TEXT,
    completed_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (job_id)
);

-- =====================================================
-- VERSION CONTROL & HISTORY
-- =====================================================

-- Versions
CREATE TABLE IF NOT EXISTS versions (
    version_key                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key                 BIGINT NOT NULL,
    job_id                      VARCHAR(26),
    name                        VARCHAR(255) NOT NULL DEFAULT '',
    schema_data                 JSONB NOT NULL,
    description                 VARCHAR(1000) NOT NULL DEFAULT '',
    design_verification_status  design_verification_status_type NOT NULL DEFAULT 'QUEUED',
    verification_result         JSONB,
    is_public                   BOOLEAN NOT NULL DEFAULT false,
    vector                      vector(1536),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at                  TIMESTAMPTZ,
    PRIMARY KEY (version_key),
    CONSTRAINT fk_versions_async_job FOREIGN KEY (job_id) REFERENCES async_jobs(job_id)
);

-- Snapshots
CREATE TABLE IF NOT EXISTS snapshots (
    snapshot_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key   BIGINT NOT NULL,
    created_by    INTEGER NOT NULL,
    name          VARCHAR(500) NOT NULL DEFAULT '',
    schema_data   JSONB NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ,
    PRIMARY KEY (snapshot_key),
    UNIQUE (project_key, name)
);

-- Edit history
CREATE TABLE IF NOT EXISTS edit_history (
    edit_history_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_key          INTEGER NOT NULL,
    project_key       BIGINT NOT NULL,
    target_key        BIGINT,
    target_type       VARCHAR(50) CHECK (target_type IN ('TABLE', 'COLUMN', 'RELATION')),
    action_type       VARCHAR(50) NOT NULL CHECK (action_type IN ('ADD', 'UPDATE', 'RENAME', 'DELETE')),
    delta             JSONB,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    before_state      JSONB,
    after_state       JSONB,
    PRIMARY KEY (edit_history_key)
);

-- =====================================================
-- CODE GENERATION & DATA MODELS
-- =====================================================

-- Data models
CREATE TABLE IF NOT EXISTS data_models (
    model_key        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_key      BIGINT NOT NULL,
    name             VARCHAR(500) NOT NULL,
    type             VARCHAR(50) NOT NULL CHECK (type IN ('ENTITY', 'DTO_REQUEST', 'DTO_RESPONSE')),
    source_table_key BIGINT,
    last_synced_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ,
    PRIMARY KEY (model_key),
    UNIQUE (project_key, name)
);

-- Data Model - ERD Column relations
CREATE TABLE IF NOT EXISTS data_model_erd_column_relations (
    model_column_relation_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    column_key                 BIGINT NOT NULL,
    model_key                  BIGINT NOT NULL,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
--     deleted_at  TIMESTAMPTZ,
    PRIMARY KEY (model_column_relation_key),
    UNIQUE (column_key, model_key)
);

-- Mock data
CREATE TABLE IF NOT EXISTS mock_data (
    mock_data_key  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_id         VARCHAR(26) NOT NULL,
    version_key    BIGINT NOT NULL,
    file_name      VARCHAR(500),
    file_path      TEXT,
    row_counts     SMALLINT NOT NULL CHECK (row_counts > 0),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,
    PRIMARY KEY (mock_data_key),
    CONSTRAINT fk_mock_data_async_job FOREIGN KEY (job_id) REFERENCES async_jobs(job_id)
);

-- =====================================================
-- SCHEDULER & BATCH
-- =====================================================

-- Scheduler execution logs
CREATE TABLE IF NOT EXISTS scheduler_execution_logs (
    log_key           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_name          VARCHAR(100) NOT NULL,
    status            VARCHAR(20) NOT NULL CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    started_at        TIMESTAMPTZ NOT NULL,
    completed_at      TIMESTAMPTZ,
    execution_time_ms BIGINT,
    deleted_count     INTEGER DEFAULT 0,
    error_message     TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (log_key)
);
-- =====================================================
-- 02_constraints.sql
-- Foreign Key Constraints
-- =====================================================

-- User-related constraints
ALTER TABLE IF EXISTS user_social_accounts
    ADD CONSTRAINT fk_user_social_accounts_user_key FOREIGN KEY (user_key) REFERENCES users(user_key) ON DELETE CASCADE;

-- Team-related constraints
ALTER TABLE IF EXISTS teams
    ADD CONSTRAINT fk_teams_owned_by FOREIGN KEY (owned_by) REFERENCES users(user_key) ON DELETE CASCADE;

-- Team name uniqueness constraint (활성 팀만, deleted_at IS NULL인 경우)
-- PostgreSQL partial unique index
CREATE UNIQUE INDEX IF NOT EXISTS uk_teams_name_active
    ON teams (name)
    WHERE deleted_at IS NULL;

ALTER TABLE IF EXISTS user_team_relations
    ADD CONSTRAINT fk_user_team_relations_user_key FOREIGN KEY (user_key) REFERENCES users(user_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS user_team_relations
    ADD CONSTRAINT fk_user_team_relations_team_key FOREIGN KEY (team_key) REFERENCES teams(team_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS user_team_history
    ADD CONSTRAINT fk_user_team_history_team_key FOREIGN KEY (team_key) REFERENCES teams(team_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS user_team_history
    ADD CONSTRAINT fk_user_team_history_actor_key FOREIGN KEY (actor_key) REFERENCES users(user_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS user_team_history
    ADD CONSTRAINT fk_user_team_history_target_key FOREIGN KEY (target_key) REFERENCES users(user_key) ON DELETE CASCADE;

-- Project-related constraints
ALTER TABLE IF EXISTS projects
    ADD CONSTRAINT fk_projects_team_key FOREIGN KEY (team_key) REFERENCES teams(team_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS project_member_relations
    ADD CONSTRAINT fk_project_member_relations_project_key FOREIGN KEY (project_key) REFERENCES projects(project_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS project_member_relations
    ADD CONSTRAINT fk_project_member_relations_member_key FOREIGN KEY (member_key) REFERENCES users(user_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS project_member_history
    ADD CONSTRAINT fk_project_member_history_project_key FOREIGN KEY (project_key) REFERENCES projects(project_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS project_member_history
    ADD CONSTRAINT fk_project_member_history_actor_key FOREIGN KEY (actor_key) REFERENCES users(user_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS project_member_history
    ADD CONSTRAINT fk_project_member_history_target_key FOREIGN KEY (target_key) REFERENCES users(user_key) ON DELETE CASCADE;

-- ERD-related constraints
ALTER TABLE IF EXISTS erd_tables
    ADD CONSTRAINT fk_erd_tables_project_key FOREIGN KEY (project_key) REFERENCES projects(project_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS erd_columns
    ADD CONSTRAINT fk_erd_columns_table_key FOREIGN KEY (table_key) REFERENCES erd_tables(table_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS erd_relations
    ADD CONSTRAINT fk_erd_relations_project_key FOREIGN KEY (project_key) REFERENCES projects(project_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS erd_relations
    ADD CONSTRAINT fk_erd_relations_from_table_key FOREIGN KEY (from_table_key) REFERENCES erd_tables(table_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS erd_relations
    ADD CONSTRAINT fk_erd_relations_to_table_key FOREIGN KEY (to_table_key) REFERENCES erd_tables(table_key) ON DELETE CASCADE;

-- Comment-related constraints
ALTER TABLE IF EXISTS comments
    ADD CONSTRAINT fk_comments_user_key FOREIGN KEY (user_key) REFERENCES users(user_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS comments
    ADD CONSTRAINT fk_comments_table_key FOREIGN KEY (table_key) REFERENCES erd_tables(table_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS replies
    ADD CONSTRAINT fk_replies_comment_key FOREIGN KEY (comment_key) REFERENCES comments(comment_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS replies
    ADD CONSTRAINT fk_replies_user_key FOREIGN KEY (user_key) REFERENCES users(user_key) ON DELETE CASCADE;

-- Version-related constraints
ALTER TABLE IF EXISTS versions
    ADD CONSTRAINT fk_versions_project_key FOREIGN KEY (project_key) REFERENCES projects(project_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS snapshots
    ADD CONSTRAINT fk_snapshots_project_key FOREIGN KEY (project_key) REFERENCES projects(project_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS snapshots
    ADD CONSTRAINT fk_snapshots_created_by FOREIGN KEY (created_by) REFERENCES users(user_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS edit_history
    ADD CONSTRAINT fk_edit_history_user_key FOREIGN KEY (user_key) REFERENCES users(user_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS edit_history
    ADD CONSTRAINT fk_edit_history_project_key FOREIGN KEY (project_key) REFERENCES projects(project_key) ON DELETE CASCADE;

-- Data model-related constraints
ALTER TABLE IF EXISTS data_models
    ADD CONSTRAINT fk_data_models_project_key FOREIGN KEY (project_key) REFERENCES projects(project_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS data_model_erd_column_relations
    ADD CONSTRAINT fk_data_model_erd_column_relations_column_key FOREIGN KEY (column_key) REFERENCES erd_columns(column_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS data_model_erd_column_relations
    ADD CONSTRAINT fk_data_model_erd_column_relations_model_key FOREIGN KEY (model_key) REFERENCES data_models(model_key) ON DELETE CASCADE;

ALTER TABLE IF EXISTS data_models
    ADD CONSTRAINT fk_data_models_source_table_key FOREIGN KEY (source_table_key) REFERENCES erd_tables(table_key) ON DELETE SET NULL;

-- Mock data constraints
ALTER TABLE IF EXISTS mock_data
    ADD CONSTRAINT fk_mock_data_version_key FOREIGN KEY (version_key) REFERENCES versions(version_key) ON DELETE CASCADE;

-- Notification constraints
ALTER TABLE IF EXISTS notifications
    ADD CONSTRAINT fk_notifications_user_key FOREIGN KEY (user_key) REFERENCES users(user_key) ON DELETE CASCADE;

-- =====================================================
-- 03_indexes.sql
-- Database Indexes for Performance
-- =====================================================

-- Partial UNIQUE indexes for soft delete support
CREATE UNIQUE INDEX idx_users_email_active ON users(email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_users_nickname_active ON users(nickname) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_teams_owner_name_active ON teams(owned_by, name) WHERE deleted_at IS NULL;

-- Performance indexes for foreign keys
CREATE INDEX idx_snapshots_project_key ON snapshots(project_key);
CREATE INDEX idx_erd_columns_table_key ON erd_columns(table_key);
CREATE INDEX idx_comments_table_key ON comments(table_key);
CREATE INDEX idx_comments_user_key ON comments(user_key);
CREATE INDEX idx_versions_project_key ON versions(project_key);
CREATE INDEX idx_erd_tables_project_key ON erd_tables(project_key);
CREATE INDEX idx_erd_relations_project_key ON erd_relations(project_key);
CREATE INDEX idx_erd_relations_from_table_key ON erd_relations(from_table_key);
CREATE INDEX idx_erd_relations_to_table_key ON erd_relations(to_table_key);
CREATE INDEX idx_replies_comment_key ON replies(comment_key);
CREATE INDEX idx_replies_user_key ON replies(user_key);
CREATE INDEX idx_notifications_user_key ON notifications(user_key);
CREATE INDEX idx_data_model_erd_column_relations_column_key ON data_model_erd_column_relations(column_key);
CREATE INDEX idx_data_model_erd_column_relations_model_key ON data_model_erd_column_relations(model_key);

-- Soft delete indexes (for filtering deleted records)
CREATE INDEX idx_users_deleted_at ON users(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_teams_deleted_at ON teams(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_projects_deleted_at ON projects(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_erd_tables_deleted_at ON erd_tables(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_erd_relations_deleted_at ON erd_relations(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_erd_columns_deleted_at ON erd_columns(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_comments_deleted_at ON comments(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_replies_deleted_at ON replies(deleted_at) WHERE deleted_at IS NULL;

-- Composite indexes for common queries
CREATE INDEX idx_notifications_user_read ON notifications(user_key, read_at);
CREATE INDEX idx_versions_project_public ON versions(project_key, is_public);

-- Additional performance indexes
CREATE INDEX idx_projects_team_key ON projects(team_key);
CREATE INDEX idx_teams_owned_by ON teams(owned_by);
CREATE INDEX idx_edit_history_project_key ON edit_history(project_key);
CREATE INDEX idx_edit_history_user_key ON edit_history(user_key);
CREATE INDEX idx_user_team_history_team_key ON user_team_history(team_key);
CREATE INDEX idx_project_member_history_project_key ON project_member_history(project_key);
CREATE INDEX idx_data_models_project_key ON data_models(project_key);
CREATE INDEX idx_data_models_source_table_key ON data_models(source_table_key);
CREATE INDEX idx_data_models_last_synced_at ON data_models(last_synced_at);
CREATE INDEX idx_mock_data_version_key ON mock_data(version_key);

-- Timestamp-based indexes for queries sorted by creation/update time
CREATE INDEX idx_comments_created_at ON comments(created_at DESC);
CREATE INDEX idx_replies_created_at ON replies(created_at DESC);
CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX idx_versions_created_at ON versions(created_at DESC);
-- =====================================================
-- 04_triggers.sql
-- Soft Delete Cascade Triggers
-- =====================================================

-- Team 삭제 시 하위 Projects도 soft delete
CREATE OR REPLACE FUNCTION soft_delete_cascade_team_projects()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN
        UPDATE projects
        SET deleted_at = NEW.deleted_at
        WHERE team_key = NEW.team_key
          AND deleted_at IS NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_soft_delete_cascade_team_projects
AFTER UPDATE ON teams
FOR EACH ROW
EXECUTE FUNCTION soft_delete_cascade_team_projects();

-- Project 삭제 시 하위 ERD Tables, Versions, Data Models도 soft delete
CREATE OR REPLACE FUNCTION soft_delete_cascade_project_children()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN
        -- ERD Tables 삭제
        UPDATE erd_tables
        SET deleted_at = NEW.deleted_at
        WHERE project_key = NEW.project_key
          AND deleted_at IS NULL;

        -- Versions 삭제
        UPDATE versions
        SET deleted_at = NEW.deleted_at
        WHERE project_key = NEW.project_key
          AND deleted_at IS NULL;

        -- Data Models 삭제
        UPDATE data_models
        SET deleted_at = NEW.deleted_at
        WHERE project_key = NEW.project_key
          AND deleted_at IS NULL;

        -- Snapshots 삭제
        UPDATE snapshots
        SET deleted_at = NEW.deleted_at
        WHERE project_key = NEW.project_key
          AND deleted_at IS NULL;

        -- ERD Relations 삭제 (project_key로 직접 참조)
        UPDATE erd_relations
        SET deleted_at = NEW.deleted_at
        WHERE project_key = NEW.project_key
          AND deleted_at IS NULL;

        -- Comments 삭제 (table_key를 통해 간접 참조)
        UPDATE comments
        SET deleted_at = NEW.deleted_at
        WHERE table_key IN (
            SELECT table_key FROM erd_tables WHERE project_key = NEW.project_key
        ) AND deleted_at IS NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_soft_delete_cascade_project_children
AFTER UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION soft_delete_cascade_project_children();

-- Table 삭제 시 하위 Columns와 Relations도 soft delete
CREATE OR REPLACE FUNCTION soft_delete_cascade_table_children()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN
        -- Columns 삭제
        UPDATE erd_columns
        SET deleted_at = NEW.deleted_at
        WHERE table_key = NEW.table_key
          AND deleted_at IS NULL;

        -- Relations 삭제 (from_table 또는 to_table)
        UPDATE erd_relations
        SET deleted_at = NEW.deleted_at
        WHERE (from_table_key = NEW.table_key OR to_table_key = NEW.table_key)
          AND deleted_at IS NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_soft_delete_cascade_table_children
AFTER UPDATE ON erd_tables
FOR EACH ROW
EXECUTE FUNCTION soft_delete_cascade_table_children();

-- Version 삭제 시 하위 Mock Data도 soft delete
CREATE OR REPLACE FUNCTION soft_delete_cascade_version_children()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN
        -- Mock Data 삭제
        UPDATE mock_data
        SET deleted_at = NEW.deleted_at
        WHERE version_key = NEW.version_key
          AND deleted_at IS NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_soft_delete_cascade_version_children
AFTER UPDATE ON versions
FOR EACH ROW
EXECUTE FUNCTION soft_delete_cascade_version_children();

-- User 삭제 시 연관 데이터 처리
CREATE OR REPLACE FUNCTION soft_delete_cascade_user_data()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN
        -- 1. User Social Accounts 완전 삭제
        DELETE FROM user_social_accounts
        WHERE user_key = NEW.user_key;

        -- 2. Snapshots 완전 삭제
        DELETE FROM snapshots
        WHERE created_by = NEW.user_key;

        -- 3. Comments & Replies Soft Delete
        UPDATE comments
        SET deleted_at = NEW.deleted_at
        WHERE user_key = NEW.user_key
          AND deleted_at IS NULL;

        UPDATE replies
        SET deleted_at = NEW.deleted_at
        WHERE user_key = NEW.user_key
          AND deleted_at IS NULL;

        -- 4. Notifications 완전 삭제
        DELETE FROM notifications
        WHERE user_key = NEW.user_key;

        -- 5. Edit History 완전 삭제
        DELETE FROM edit_history
        WHERE user_key = NEW.user_key;

        -- 6. User Team History -> MEMBER_WITHDRAWAL 이력 삽입 (Relations 삭제 전에 먼저!)
        INSERT INTO user_team_history (team_key, actor_key, target_key, email, action_type, reason, created_at, updated_at)
        SELECT
            utr.team_key,
            NEW.user_key,
            NEW.user_key,
            NEW.email,
            'MEMBER_WITHDRAWAL',
            'User account deleted',
            NEW.deleted_at,
            NEW.deleted_at
        FROM user_team_relations utr
        WHERE utr.user_key = NEW.user_key;

        -- 7. User Team Relations 완전 삭제
        DELETE FROM user_team_relations
        WHERE user_key = NEW.user_key;

        -- 8. Project Member History -> WITHDRAWAL 이력 삽입 (Relations 삭제 전에 먼저!)
        INSERT INTO project_member_history (project_key, actor_key, target_key, action_type, created_at)
        SELECT
            pmr.project_key,
            NEW.user_key,
            NEW.user_key,
            'WITHDRAWAL',
            NEW.deleted_at
        FROM project_member_relations pmr
        WHERE pmr.member_key = NEW.user_key;

        -- 9. Project Member Relations 완전 삭제
        DELETE FROM project_member_relations
        WHERE member_key = NEW.user_key;

    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_soft_delete_cascade_user_data
AFTER UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION soft_delete_cascade_user_data();

-- User 재가입 시 연관 데이터 복구 및 이력 기록
CREATE OR REPLACE FUNCTION restore_user_on_reactivation()
RETURNS TRIGGER AS $$
BEGIN
    -- deleted_at이 NULL로 변경된 경우 (재가입)
    IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
        -- Comments & Replies 복구
        UPDATE comments
        SET deleted_at = NULL
        WHERE user_key = NEW.user_key
          AND deleted_at = OLD.deleted_at;

        UPDATE replies
        SET deleted_at = NULL
        WHERE user_key = NEW.user_key
          AND deleted_at = OLD.deleted_at;

        -- User Team History -> MEMBER_REJOIN 이력 삽입 및 멤버십 복구
        -- 재가입 전에 MEMBER_WITHDRAWAL 이력이 있는 팀들에 대해 REJOIN 기록
        INSERT INTO user_team_history (team_key, actor_key, target_key, email, action_type, reason, created_at, updated_at)
        SELECT DISTINCT
            uth.team_key,
            NEW.user_key,
            NEW.user_key,
            NEW.email,
            'MEMBER_REJOIN',
            'User account reactivated',
            now(),
            now()
        FROM user_team_history uth
        WHERE uth.target_key = NEW.user_key
          AND uth.action_type = 'MEMBER_WITHDRAWAL'
          AND uth.created_at >= OLD.deleted_at;

        -- User Team Relations 복구 (팀 멤버십 재추가)
        INSERT INTO user_team_relations (user_key, team_key, created_at, updated_at)
        SELECT DISTINCT
            NEW.user_key,
            uth.team_key,
            now(),
            now()
        FROM user_team_history uth
        WHERE uth.target_key = NEW.user_key
          AND uth.action_type = 'MEMBER_WITHDRAWAL'
          AND uth.created_at >= OLD.deleted_at
        ON CONFLICT (user_key, team_key) DO NOTHING;  -- 이미 존재하면 무시

        -- Project Member History -> REJOIN 이력 삽입 및 멤버십 복구
        -- 재가입 전에 WITHDRAWAL 이력이 있는 프로젝트들에 대해 REJOIN 기록
        INSERT INTO project_member_history (project_key, actor_key, target_key, action_type, created_at)
        SELECT DISTINCT
            pmh.project_key,
            NEW.user_key,
            NEW.user_key,
            'REJOIN',
            now()
        FROM project_member_history pmh
        WHERE pmh.target_key = NEW.user_key
          AND pmh.action_type = 'WITHDRAWAL'
          AND pmh.created_at >= OLD.deleted_at;

        -- Project Member Relations 복구 (프로젝트 멤버십 재추가)
        INSERT INTO project_member_relations (project_key, member_key, role, created_at, updated_at)
        SELECT DISTINCT
            pmh.project_key,
            NEW.user_key,
            'EDITOR'::project_member_role_type,  -- 기본 역할로 복구 (타입 캐스팅)
            now(),
            now()
        FROM project_member_history pmh
        WHERE pmh.target_key = NEW.user_key
          AND pmh.action_type = 'WITHDRAWAL'
          AND pmh.created_at >= OLD.deleted_at
        ON CONFLICT (project_key, member_key) DO NOTHING;  -- 이미 존재하면 무시

        -- 참고: user_social_accounts, notifications 등 완전 삭제된 데이터는 복구 불가
        -- 필요시 애플리케이션 레벨에서 재생성 필요
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_restore_user_on_reactivation
AFTER UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION restore_user_on_reactivation();

-- Team 복구 시 하위 Projects도 복구
CREATE OR REPLACE FUNCTION restore_team_children()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
        -- Projects 복구 (같은 시간에 삭제된 것만)
        UPDATE projects
        SET deleted_at = NULL
        WHERE team_key = NEW.team_key
          AND deleted_at = OLD.deleted_at;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_restore_team_children
AFTER UPDATE ON teams
FOR EACH ROW
EXECUTE FUNCTION restore_team_children();

-- Project 복구 시 하위 ERD Tables, Versions, Data Models도 복구
CREATE OR REPLACE FUNCTION restore_project_children()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
        -- ERD Tables 복구
        UPDATE erd_tables
        SET deleted_at = NULL
        WHERE project_key = NEW.project_key
          AND deleted_at = OLD.deleted_at;

        -- Versions 복구
        UPDATE versions
        SET deleted_at = NULL
        WHERE project_key = NEW.project_key
          AND deleted_at = OLD.deleted_at;

        -- Data Models 복구
        UPDATE data_models
        SET deleted_at = NULL
        WHERE project_key = NEW.project_key
          AND deleted_at = OLD.deleted_at;

        -- Snapshots 복구
        UPDATE snapshots
        SET deleted_at = NULL
        WHERE project_key = NEW.project_key
          AND deleted_at = OLD.deleted_at;

        -- ERD Relations 복구 (project_key로 직접 참조)
        UPDATE erd_relations
        SET deleted_at = NULL
        WHERE project_key = NEW.project_key
          AND deleted_at = OLD.deleted_at;

        -- Comments 복구 (table_key를 통해 간접 참조)
        UPDATE comments
        SET deleted_at = NULL
        WHERE table_key IN (
            SELECT table_key FROM erd_tables WHERE project_key = NEW.project_key
        ) AND deleted_at = OLD.deleted_at;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_restore_project_children
AFTER UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION restore_project_children();

-- ERD Table 복구 시 하위 Columns와 Relations도 복구
CREATE OR REPLACE FUNCTION restore_table_children()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
        -- Columns 복구
        UPDATE erd_columns
        SET deleted_at = NULL
        WHERE table_key = NEW.table_key
          AND deleted_at = OLD.deleted_at;

        -- Relations 복구 (from_table 또는 to_table)
        UPDATE erd_relations
        SET deleted_at = NULL
        WHERE (from_table_key = NEW.table_key OR to_table_key = NEW.table_key)
          AND deleted_at = OLD.deleted_at;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_restore_table_children
AFTER UPDATE ON erd_tables
FOR EACH ROW
EXECUTE FUNCTION restore_table_children();

-- Version 복구 시 하위 Mock Data도 복구
CREATE OR REPLACE FUNCTION restore_version_children()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
        -- Mock Data 복구
        UPDATE mock_data
        SET deleted_at = NULL
        WHERE version_key = NEW.version_key
          AND deleted_at = OLD.deleted_at;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_restore_version_children
AFTER UPDATE ON versions
FOR EACH ROW
EXECUTE FUNCTION restore_version_children();

-- =====================================================
-- Last Activity Update Triggers
-- =====================================================

-- Project의 last_activity_at 자동 업데이트 함수
-- 주의: Project 자체의 생성/수정은 JPA Entity의 @PrePersist/@PreUpdate에서 처리됨
-- 이 함수는 하위 엔티티(ERD Tables, Columns 등) 변경 시에만 사용됨
CREATE OR REPLACE FUNCTION update_project_last_activity()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE projects
    SET last_activity_at = now()
    WHERE project_key = COALESCE(NEW.project_key, OLD.project_key);

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- ERD Tables 변경 시
CREATE TRIGGER trigger_update_project_activity_on_table_change
AFTER INSERT OR UPDATE OR DELETE ON erd_tables
FOR EACH ROW
EXECUTE FUNCTION update_project_last_activity();

-- ERD Columns 변경 시 (project_key는 erd_tables를 통해 찾음)
CREATE OR REPLACE FUNCTION update_project_last_activity_via_table()
RETURNS TRIGGER AS $$
DECLARE
    v_project_key BIGINT;
BEGIN
    SELECT project_key INTO v_project_key
    FROM erd_tables
    WHERE table_key = COALESCE(NEW.table_key, OLD.table_key);

    IF v_project_key IS NOT NULL THEN
        UPDATE projects
        SET last_activity_at = now()
        WHERE project_key = v_project_key;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_project_activity_on_column_change
AFTER INSERT OR UPDATE OR DELETE ON erd_columns
FOR EACH ROW
EXECUTE FUNCTION update_project_last_activity_via_table();

-- ERD Relations 변경 시
CREATE TRIGGER trigger_update_project_activity_on_relation_change
AFTER INSERT OR UPDATE OR DELETE ON erd_relations
FOR EACH ROW
EXECUTE FUNCTION update_project_last_activity();

-- Comments 변경 시 (table_key를 통해 project_key 찾음)
CREATE TRIGGER trigger_update_project_activity_on_comment_change
AFTER INSERT OR UPDATE OR DELETE ON comments
FOR EACH ROW
EXECUTE FUNCTION update_project_last_activity_via_table();

-- Replies 변경 시 (comment_key -> table_key -> project_key)
CREATE OR REPLACE FUNCTION update_project_last_activity_via_comment()
RETURNS TRIGGER AS $$
DECLARE
    v_project_key BIGINT;
BEGIN
    SELECT et.project_key INTO v_project_key
    FROM comments c
    JOIN erd_tables et ON c.table_key = et.table_key
    WHERE c.comment_key = COALESCE(NEW.comment_key, OLD.comment_key);

    IF v_project_key IS NOT NULL THEN
        UPDATE projects
        SET last_activity_at = now()
        WHERE project_key = v_project_key;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_project_activity_on_reply_change
AFTER INSERT OR UPDATE OR DELETE ON replies
FOR EACH ROW
EXECUTE FUNCTION update_project_last_activity_via_comment();

-- Versions 변경 시
CREATE TRIGGER trigger_update_project_activity_on_version_change
AFTER INSERT OR UPDATE OR DELETE ON versions
FOR EACH ROW
EXECUTE FUNCTION update_project_last_activity();

-- Data Models 변경 시
CREATE TRIGGER trigger_update_project_activity_on_datamodel_change
AFTER INSERT OR UPDATE OR DELETE ON data_models
FOR EACH ROW
EXECUTE FUNCTION update_project_last_activity();

-- Edit History 추가 시 (project_key를 직접 사용)
CREATE TRIGGER trigger_update_project_activity_on_edit_history
AFTER INSERT ON edit_history
FOR EACH ROW
EXECUTE FUNCTION update_project_last_activity();
