import MiniMap, { MiniMapOverlay } from './rightsidebar/MiniMap';
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import AiChat from './rightsidebar/AiChat';
import Chat from './rightsidebar/Chat';
import Dto from './rightsidebar/Dto';
import type { DtoColumnInfo } from '../../types/dataModel';
import EditProjectModal from '../project/EditProjectModal';
import Entity from './rightsidebar/Entity';
import History from './rightsidebar/History';
import ModalSmall from '../../components/common/ModalSmall';
import Setting from './rightsidebar/Setting';
import Share from './rightsidebar/Share';
import SnapShot from './rightsidebar/SnapShot';
import VersionSave from './rightsidebar/VersionSave';
import ZoomIn from './rightsidebar/ZoomIn';
import ZoomOut from './rightsidebar/ZoomOut';
import { createDto } from './rightsidebar/Dto';
import { createEntity } from './rightsidebar/entityApi';
import { useDataModelStore } from '../../stores/dataModelStore';
import { useDtoSelectionStore } from '../../stores/dtoSelectionStore';
import { useEntitySelectionStore } from '../../stores/entitySelectionStore';
import { useGetProjectInfo } from '../../hooks/useGetProjectInfo';
import { useWorkspace } from './WorkSpace';

type DtoKind = 'requestDto' | 'responseDto';

const ensureDtoName = (name: string): string => {
  const trimmed = name.trim();
  if (!trimmed) {
    return 'NewDto';
  }
  // 간단한 Pascal Case 변환
  const pascal = trimmed
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  return pascal.endsWith('Dto') ? pascal : `${pascal}Dto`;
};

const stripDuplicateSuffix = (name: string): string => {
  return name.replace(/\s*\(\d+\)$/, '').trim();
};

const createUniqueDtoName = (name: string, existingNames: string[]): string => {
  const normalizedExisting = new Set(
    existingNames.map((existing) => existing.toLowerCase()),
  );
  const baseName = ensureDtoName(stripDuplicateSuffix(name));

  if (!normalizedExisting.has(baseName.toLowerCase())) {
    return baseName;
  }

  let counter = 1;
  while (true) {
    const candidate = `${baseName} (${counter})`;
    if (!normalizedExisting.has(candidate.toLowerCase())) {
      return candidate;
    }
    counter += 1;
  }
};

const MIN_ZOOM = 0.1;
const MAX_ZOOM = 2;
const ZOOM_IN_FACTOR = 1.1;
const ZOOM_OUT_FACTOR = 0.9;
const ZOOM_EPSILON = 0.0001;

const RightSideBar: React.FC = () => {
  const { zoom, setZoom, setPan, tables } = useWorkspace();
  const [isMiniMapOpen, setIsMiniMapOpen] = useState(false);
  const [activePanel, setActivePanel] = useState<
    'snapshot' | 'history' | 'comments' | 'ai' | null
  >(null);
  const [activeModalCount, setActiveModalCount] = useState(0);
  const [isDtoResultModalOpen, setIsDtoResultModalOpen] = useState(false);
  const [lastGeneratedDtoCount, setLastGeneratedDtoCount] = useState(0);
  const [lastGeneratedDtoNames, setLastGeneratedDtoNames] = useState<string[]>(
    [],
  );
  const [lastGeneratedFieldCount, setLastGeneratedFieldCount] = useState(0);
  const [dtoNameInput, setDtoNameInput] = useState('');
  const [dtoType, setDtoType] = useState<DtoKind>('responseDto');
  const hasAutoGeneratedDtoName = useRef(false);
  const [isEntityConfirmModalOpen, setIsEntityConfirmModalOpen] =
    useState(false);
  const [selectedEntityInfo, setSelectedEntityInfo] = useState<{
    name: string;
  } | null>(null);
  const [isSettingModalOpen, setIsSettingModalOpen] = useState(false);

  const isDtoSelecting = useDtoSelectionStore((state) => state.isSelecting);
  const startDtoSelection = useDtoSelectionStore(
    (state) => state.startSelection,
  );
  const cancelDtoSelection = useDtoSelectionStore(
    (state) => state.cancelSelection,
  );
  const selectedDtoColumns = useDtoSelectionStore(
    (state) => state.selectedColumns,
  );
  const isEntitySelecting = useEntitySelectionStore(
    (state) => state.isSelecting,
  );
  const startEntitySelection = useEntitySelectionStore(
    (state) => state.startSelection,
  );
  const cancelEntitySelection = useEntitySelectionStore(
    (state) => state.cancelSelection,
  );
  const selectedEntityTableId = useEntitySelectionStore(
    (state) => state.selectedTableId,
  );

  const dataModels = useDataModelStore((state) => state.dataModels);
  const navigate = useNavigate();
  const { projectKey } = useParams();

  const { data: projectInfo } = useGetProjectInfo(
    projectKey ? Number(projectKey) : undefined,
  );

  const handleModalChange = useCallback((isOpen: boolean) => {
    setActiveModalCount((prev) => {
      const next = prev + (isOpen ? 1 : -1);
      return next < 0 ? 0 : next;
    });
  }, []);

  const isDimmed = activeModalCount > 0;

  const selectedEntityTable = useMemo(() => {
    if (!selectedEntityTableId) {
      return null;
    }
    return tables.find((table) => table.id === selectedEntityTableId) ?? null;
  }, [selectedEntityTableId, tables]);

  const existingDtoNames = useMemo(
    () =>
      dataModels
        .filter(
          (item) => item.type === 'requestDto' || item.type === 'responseDto',
        )
        .map((item) => item.name),
    [dataModels],
  );

  const togglePanel = (panel: 'snapshot' | 'history' | 'comments' | 'ai') => {
    setActivePanel((prev) => (prev === panel ? null : panel));
  };

  const clampZoom = useCallback(
    (value: number) => Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, value)),
    [],
  );

  const handleZoomChange = useCallback(
    (direction: 'in' | 'out') => {
      const zoomMultiplier =
        direction === 'in' ? ZOOM_IN_FACTOR : ZOOM_OUT_FACTOR;
      const canvasElement = document.querySelector<HTMLDivElement>(
        '[data-workspace-canvas="true"]',
      );
      const canvasRect = canvasElement?.getBoundingClientRect();
      const focalPoint = canvasRect
        ? { x: canvasRect.width / 2, y: canvasRect.height / 2 }
        : null;

      setZoom((prevZoom) => {
        const nextZoom = clampZoom(prevZoom * zoomMultiplier);
        if (nextZoom === prevZoom) {
          return prevZoom;
        }

        if (focalPoint) {
          setPan((prevPan) => {
            const worldX = (focalPoint.x - prevPan.x) / prevZoom;
            const worldY = (focalPoint.y - prevPan.y) / prevZoom;

            const nextPanX = focalPoint.x - worldX * nextZoom;
            const nextPanY = focalPoint.y - worldY * nextZoom;

            if (
              Math.abs(nextPanX - prevPan.x) < ZOOM_EPSILON &&
              Math.abs(nextPanY - prevPan.y) < ZOOM_EPSILON
            ) {
              return prevPan;
            }

            return { x: nextPanX, y: nextPanY };
          });
        }

        return nextZoom;
      });
    },
    [clampZoom, setPan, setZoom],
  );

  const handleZoomIn = useCallback(
    () => handleZoomChange('in'),
    [handleZoomChange],
  );
  const handleZoomOut = useCallback(
    () => handleZoomChange('out'),
    [handleZoomChange],
  );

  const closeDtoResultModal = useCallback(() => {
    setIsDtoResultModalOpen(false);
    handleModalChange(false);
  }, [handleModalChange]);

  const handleNavigateToDataModel = () => {
    closeDtoResultModal();
    if (!projectKey) {
      return;
    }
    navigate(`/project/${projectKey}/data-model`);
  };

  useEffect(() => {
    if (!isDtoSelecting) {
      hasAutoGeneratedDtoName.current = false;
      setDtoNameInput('');
      setDtoType('responseDto');
      return;
    }

    if (dtoNameInput || hasAutoGeneratedDtoName.current) {
      return;
    }

    hasAutoGeneratedDtoName.current = true;
  }, [dtoNameInput, existingDtoNames, isDtoSelecting, tables]);

  const selectedColumnCount = useMemo(() => {
    if (!isDtoSelecting) {
      return 0;
    }
    return Object.keys(selectedDtoColumns).length;
  }, [isDtoSelecting, selectedDtoColumns]);

  const handleCancelSelection = useCallback(() => {
    cancelDtoSelection();
    setDtoNameInput('');
    setDtoType('responseDto');
  }, [cancelDtoSelection]);

  const handleDtoButtonClick = useCallback(() => {
    if (isDtoSelecting) {
      handleCancelSelection();
      return;
    }
    if (isEntitySelecting) {
      cancelEntitySelection();
    }
    setActivePanel(null);
    setDtoNameInput('');
    setDtoType('responseDto');
    startDtoSelection();
  }, [
    cancelEntitySelection,
    handleCancelSelection,
    isDtoSelecting,
    isEntitySelecting,
    setActivePanel,
    startDtoSelection,
  ]);

  const handleCompleteSelection = useCallback(async () => {
    if (selectedColumnCount === 0) {
      return;
    }

    const selectedColumns: DtoColumnInfo[] = [];
    const apiSelectedColumns: { columnKey: number; tableKey: number }[] = [];

    tables.forEach((table) => {
      table.columns.forEach((column) => {
        const key = `${table.id}:${column.id}`;
        if (selectedDtoColumns[key]) {
          selectedColumns.push({
            ...column,
            sourceTableId: table.id,
            sourceTableName: table.name,
            sourceTableIdentifier: table.identifier,
          });

          // API용 데이터 수집
          if (table.key && column.key) {
            apiSelectedColumns.push({
              columnKey: column.key,
              tableKey: table.key,
            });
          }
        }
      });
    });

    if (selectedColumns.length === 0) {
      return;
    }

    const fallbackBase = tables[0]?.name ?? 'SelectedColumns';
    const displayName = createUniqueDtoName(
      dtoNameInput || fallbackBase,
      existingDtoNames,
    );

    console.log('DTO 생성 시도:', {
      projectKey,
      apiSelectedColumns,
      selectedColumnsCount: selectedColumns.length,
    });

    // 백엔드 API 호출
    if (projectKey && apiSelectedColumns.length > 0) {
      try {
        await createDto(Number(projectKey), {
          name: displayName,
          type: dtoType === 'responseDto' ? 'DTO_RESPONSE' : 'DTO_REQUEST',
          selectedColumns: apiSelectedColumns,
        });
        console.log('DTO 백엔드 저장 성공');

        setLastGeneratedDtoCount(1);
        setLastGeneratedDtoNames([displayName]);
        setLastGeneratedFieldCount(selectedColumns.length);
        cancelDtoSelection();
        setDtoNameInput('');
        setDtoType('responseDto');
        setIsDtoResultModalOpen(true);
        handleModalChange(true);
      } catch (error) {
        console.error('DTO 백엔드 저장 실패:', error);
        cancelDtoSelection();
        setDtoNameInput('');
        setDtoType('responseDto');
      }
    }
  }, [
    cancelDtoSelection,
    dtoNameInput,
    dtoType,
    handleModalChange,
    existingDtoNames,
    selectedColumnCount,
    selectedDtoColumns,
    tables,
    projectKey,
  ]);

  const handleEntityButtonClick = useCallback(() => {
    if (isEntitySelecting) {
      cancelEntitySelection();
      return;
    }
    if (isDtoSelecting) {
      handleCancelSelection();
    }
    setActivePanel(null);
    startEntitySelection();
  }, [
    cancelEntitySelection,
    handleCancelSelection,
    isDtoSelecting,
    isEntitySelecting,
    setActivePanel,
    startEntitySelection,
  ]);

  const handleEntityCancel = useCallback(() => {
    cancelEntitySelection();
  }, [cancelEntitySelection]);

  const handleEntityConfirm = useCallback(async () => {
    if (!selectedEntityTable || !selectedEntityTable.key || !projectKey) {
      return;
    }

    try {
      console.log('Entity 생성 시도:', {
        projectKey,
        tableKey: selectedEntityTable.key,
        tableName: selectedEntityTable.name,
      });

      await createEntity(Number(projectKey), selectedEntityTable.key);
      console.log('Entity 백엔드 저장 성공');

      setSelectedEntityInfo({
        name: selectedEntityTable.name,
      });
      cancelEntitySelection();
      setIsEntityConfirmModalOpen(true);
      handleModalChange(true);
    } catch (error) {
      console.error('Entity 백엔드 저장 실패:', error);
      cancelEntitySelection();
    }
  }, [
    cancelEntitySelection,
    handleModalChange,
    selectedEntityTable,
    projectKey,
  ]);

  const closeEntityConfirmModal = useCallback(() => {
    setIsEntityConfirmModalOpen(false);
    setSelectedEntityInfo(null);
    handleModalChange(false);
  }, [handleModalChange]);

  const handleEntityStay = useCallback(() => {
    closeEntityConfirmModal();
  }, [closeEntityConfirmModal]);

  const handleEntityNavigate = useCallback(() => {
    closeEntityConfirmModal();
    if (!projectKey) {
      return;
    }
    navigate(`/project/${projectKey}/data-model`);
  }, [closeEntityConfirmModal, navigate, projectKey]);

  const isZoomInDisabled = zoom >= MAX_ZOOM - ZOOM_EPSILON;
  const isZoomOutDisabled = zoom <= MIN_ZOOM + ZOOM_EPSILON;

  return (
    <>
      {isEntitySelecting ? (
        <div className="fixed right-20 top-28 z-50 w-72 rounded-2xl border border-my-border bg-white p-5 shadow-2xl">
          <div className="flex flex-col gap-4">
            <h3 className="text-base font-semibold text-my-black">
              Entity 선택
            </h3>
            <p className="text-xs leading-relaxed text-my-gray-500">
              체크박스를 사용해 엔티티로 만들 테이블을 한 개만 선택하세요.
            </p>
            <div className="rounded-lg border border-dashed border-my-border px-3 py-2">
              <span className="text-xs text-my-gray-500">선택된 테이블</span>
              <span className="block text-sm font-semibold text-my-black">
                {selectedEntityTable ? selectedEntityTable.name : '없음'}
              </span>
            </div>
            <div className="flex justify-end gap-2">
              <button
                type="button"
                onClick={handleEntityCancel}
                className="rounded-lg border border-my-border px-4 py-2 text-sm text-my-gray-600 transition-colors hover:bg-gray-50"
              >
                취소
              </button>
              <button
                type="button"
                onClick={handleEntityConfirm}
                disabled={!selectedEntityTable}
                className={`rounded-lg px-4 py-2 text-sm font-semibold text-white transition-colors ${
                  selectedEntityTable
                    ? 'bg-blue hover:bg-blue/90'
                    : 'bg-light-blue'
                } disabled:cursor-not-allowed`}
              >
                확인
              </button>
            </div>
          </div>
        </div>
      ) : null}
      {isDtoSelecting ? (
        <div className="fixed right-20 top-28 z-50 w-80 rounded-2xl border border-my-border bg-white p-5 shadow-2xl">
          <div className="flex flex-col gap-4">
            <h3 className="text-base font-semibold text-my-black">DTO 설정</h3>

            <div className="flex flex-col gap-2">
              <label
                className="text-xs font-medium text-my-gray-600"
                htmlFor="dto-name-input"
              >
                DTO 이름
              </label>
              <input
                id="dto-name-input"
                value={dtoNameInput}
                onChange={(event) => setDtoNameInput(event.target.value)}
                placeholder="예: UserResponseDto"
                className="w-full rounded-lg border border-my-border px-3 py-2 text-sm focus:border-blue focus:outline-none"
              />
            </div>

            <div className="flex flex-col gap-2">
              <label
                className="text-xs font-medium text-my-gray-600"
                htmlFor="dto-type-select"
              >
                DTO 타입
              </label>
              <select
                id="dto-type-select"
                value={dtoType}
                onChange={(event) => setDtoType(event.target.value as DtoKind)}
                className="w-full rounded-lg border border-my-border px-3 py-2 text-sm focus:border-blue focus:outline-none"
              >
                <option value="responseDto">Response DTO</option>
                <option value="requestDto">Request DTO</option>
              </select>
            </div>

            <div className="flex justify-end gap-2">
              <button
                type="button"
                onClick={handleCancelSelection}
                className="rounded-lg border border-my-border px-4 py-2 text-sm text-my-gray-600 hover:bg-gray-50 transition-colors"
              >
                취소
              </button>
              <button
                type="button"
                onClick={handleCompleteSelection}
                disabled={selectedColumnCount === 0}
                className={`rounded-lg px-4 py-2 text-sm font-semibold text-white transition-colors ${
                  selectedColumnCount === 0
                    ? 'bg-light-blue'
                    : 'bg-blue hover:bg-blue/90'
                } disabled:cursor-not-allowed`}
              >
                완료
              </button>
            </div>

            <p className="text-[11px] text-my-gray-400 leading-relaxed">
              워크스페이스 캔버스의 컬럼 체크박스를 사용해 DTO에 포함할 필드를
              고른 뒤 완료를 눌러주세요.
            </p>
          </div>
        </div>
      ) : null}
      <div className="w-12 bg-my-white border-l border-my-border flex flex-col items-center py-4 overflow-y-auto">
        <SnapShot
          isOpen={activePanel === 'snapshot'}
          onToggle={() => togglePanel('snapshot')}
          onClose={() => setActivePanel(null)}
          dimmed={isDimmed}
        />
        <Dto onClick={handleDtoButtonClick} isActive={isDtoSelecting} />
        <Entity
          onClick={handleEntityButtonClick}
          isActive={isEntitySelecting}
        />
        <VersionSave onModalChange={handleModalChange} />
        <History
          isOpen={activePanel === 'history'}
          onToggle={() => togglePanel('history')}
          onClose={() => setActivePanel(null)}
          dimmed={isDimmed}
        />
        <Chat
          isOpen={activePanel === 'comments'}
          onToggle={() => togglePanel('comments')}
          onClose={() => setActivePanel(null)}
          dimmed={isDimmed}
        />
        <Share onModalChange={handleModalChange} />
        <AiChat
          isOpen={activePanel === 'ai'}
          onToggle={() => togglePanel('ai')}
          onClose={() => setActivePanel(null)}
          dimmed={isDimmed}
        />

        <div className="flex-grow" />

        <MiniMap onClick={() => setIsMiniMapOpen((prev) => !prev)} />
        <ZoomIn onClick={handleZoomIn} disabled={isZoomInDisabled} />
        <ZoomOut onClick={handleZoomOut} disabled={isZoomOutDisabled} />
        <Setting onClick={() => setIsSettingModalOpen(true)} />

        <MiniMapOverlay isOpen={isMiniMapOpen} />

        {projectInfo &&
          (projectInfo as unknown as { teamKey?: number }).teamKey && (
            <EditProjectModal
              isOpen={isSettingModalOpen}
              teamKey={(projectInfo as unknown as { teamKey: number }).teamKey}
              projectKey={Number(projectKey)}
              onClose={() => setIsSettingModalOpen(false)}
              onSuccess={() => setIsSettingModalOpen(false)}
            />
          )}

        <ModalSmall
          isOpen={isEntityConfirmModalOpen}
          onClose={closeEntityConfirmModal}
          title="Entity 선택 완료"
        >
          <div className="flex flex-col gap-6">
            <div className="flex flex-col gap-1">
              <p className="text-sm font-semibold text-my-black">
                {selectedEntityInfo
                  ? selectedEntityInfo.name
                  : '선택된 테이블이 없습니다.'}
              </p>
              <p className="text-xs text-my-gray-500">
                데이터 모델 페이지로 이동해 엔티티를 이어서 편집할 수 있습니다.
              </p>
            </div>
            <div className="flex justify-end gap-3">
              <button
                type="button"
                onClick={handleEntityStay}
                className="rounded-lg border border-my-border px-4 py-2 text-sm transition-colors hover:bg-gray-50"
              >
                워크스페이스에 남기
              </button>
              <button
                type="button"
                onClick={handleEntityNavigate}
                className="rounded-lg bg-blue px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-blue/90"
              >
                데이터 모델로 이동
              </button>
            </div>
          </div>
        </ModalSmall>

        <ModalSmall
          isOpen={isDtoResultModalOpen}
          onClose={closeDtoResultModal}
          title="DTO 추출 완료"
        >
          <div className="flex flex-col gap-6">
            <p className="text-sm text-my-gray-600">
              총 {lastGeneratedDtoCount}개의 DTO를 데이터 모델에 추가했습니다.
            </p>
            <p className="text-xs text-my-gray-400">
              {lastGeneratedDtoNames.join(', ')} · 컬럼{' '}
              {lastGeneratedFieldCount}개
            </p>
            <p className="text-xs text-my-gray-400">
              데이터 모델 페이지에서 내용을 확인하고 편집할 수 있습니다.
            </p>
            <div className="flex justify-end gap-3">
              <button
                type="button"
                onClick={closeDtoResultModal}
                className="px-4 py-2 border border-my-border rounded-lg text-sm hover:bg-gray-50 transition-colors"
              >
                워크스페이스에 남기
              </button>
              <button
                type="button"
                onClick={handleNavigateToDataModel}
                className="px-4 py-2 rounded-lg text-sm font-semibold text-white bg-blue hover:bg-blue/90 transition-colors"
              >
                데이터 모델로 이동
              </button>
            </div>
          </div>
        </ModalSmall>
      </div>
    </>
  );
};

export default RightSideBar;
