import React, { useCallback, useEffect, useState, useRef } from 'react';
import { useParams } from 'react-router-dom';
import LeftSideBar from './LeftSideBar';
import RightSideBar from './RightSideBar';
import WorkspaceCanvas, { type WorkspaceMode } from './WorkspaceCanvas';
import { WorkspaceProvider, useWorkspace } from './WorkSpace';
import type { WorkspaceTable, WorkspaceTableColor, WorkspaceRelation, RelationType } from './WorkSpace';
import ImportModal from './components/ImportModal';
import ExportModal from './components/ExportModal';
import ImportResultModal from './components/ImportResultModal';
import ImportRetryModal from './components/ImportRetryModal';
import type { ExportDatabase } from './components/ExportModal';
import BuildSuccessIcon from '../../assets/icons/build_success_icon.svg?react';
import { ErdWebSocketClient } from '../../services/websocket';
import { useAuthStore } from '../../stores/authStore';
import { useAiDraftStore } from '../../stores/aiDraftStore';
import RemoteCursor from './components/RemoteCursor';
import type { RemoteCursor as RemoteCursorType } from '../../services/websocket/types';
import useViewerStream from '../../hooks/useSSEViewer';
import AiDraftConfirmBanner from './components/AiDraftConfirmModal';
import { exportErdToSql, type SqlDialect } from '../../apis/exportApi';

const dummySqlPreview: Record<ExportDatabase, string> = {
  mysql: `-- MySQL Export 예시
CREATE TABLE customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO customers (name, email)
VALUES
  ('홍길동', 'hong.gildong@example.com'),
  ('김영희', 'kim.younghee@example.com');`,
  postgresql: `-- PostgreSQL Export 예시
CREATE TABLE customers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO customers (name, email)
VALUES
  ('홍길동', 'hong.gildong@example.com'),
  ('김영희', 'kim.younghee@example.com');`,
};

const IMPORT_ERROR_SQL = `CREATE TABLE "snapshots" (
  "snapshot_key" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_key" INTEGER NOT NULL,
  "created_by" INTEGER NOT NULL,
  "name" VARCHAR(500) NOT NULL DEFAULT '',
  "schema" JSONB NOT NULL DEFAULT '{}',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);`;

const IMPORT_ERROR_CHANGE_SUMMARY = [
  'snapshots.snapshot_key 컬럼을 BIGINT IDENTITY로 수정했습니다.',
  'schema 컬럼을 JSONB 타입으로 지정하여 JSON 구조 저장을 지원합니다.',
  'created_at 컬럼에 기본값 now()를 추가하여 생성 시간을 자동 저장합니다.',
];

const IMPORT_CORRECTED_TABLES: WorkspaceTable[] = [
  {
    id: 'table-projects',
    name: 'projects',
    identifier: 'projects',
    x: 180,
    y: 140,
    color: 'blue',
    columns: [
      {
        id: 'column-projects-project-key',
        isPK: true,
        isFK: false,
        logicalName: '프로젝트 키',
        physicalName: 'project_key',
        dataType: 'INTEGER',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '프로젝트 식별자',
      },
      {
        id: 'column-projects-name',
        isPK: false,
        isFK: false,
        logicalName: '프로젝트명',
        physicalName: 'name',
        dataType: 'VARCHAR(255)',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '프로젝트 이름',
      },
      {
        id: 'column-projects-owner',
        isPK: false,
        isFK: false,
        logicalName: '생성자',
        physicalName: 'created_by',
        dataType: 'INTEGER',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '프로젝트 생성자',
      },
    ],
  },
  {
    id: 'table-snapshots',
    name: 'snapshots',
    identifier: 'snapshots',
    x: 420,
    y: 120,
    color: 'user2',
    columns: [
      {
        id: 'column-snapshots-key',
        isPK: true,
        isFK: false,
        logicalName: '스냅샷 키',
        physicalName: 'snapshot_key',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: 'IDENTITY',
        comment: '스냅샷 식별자',
      },
      {
        id: 'column-snapshots-project-key',
        isPK: false,
        isFK: false,
        logicalName: '프로젝트 키',
        physicalName: 'project_key',
        dataType: 'INTEGER',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '연결된 프로젝트',
      },
      {
        id: 'column-snapshots-schema',
        isPK: false,
        isFK: false,
        logicalName: '스키마',
        physicalName: 'schema',
        dataType: 'JSONB',
        allowNull: 'NOT NULL',
        defaultValue: '{}',
        comment: 'ERD JSON 데이터',
      },
      {
        id: 'column-snapshots-created-at',
        isPK: false,
        isFK: false,
        logicalName: '생성 일시',
        physicalName: 'created_at',
        dataType: 'TIMESTAMPTZ',
        allowNull: 'NOT NULL',
        defaultValue: 'now()',
        comment: '생성 시각',
      },
    ],
  },
  {
    id: 'table-entities',
    name: 'entities',
    identifier: 'entities',
    x: 260,
    y: 340,
    color: 'user3',
    columns: [
      {
        id: 'column-entities-key',
        isPK: true,
        isFK: false,
        logicalName: '엔티티 키',
        physicalName: 'entity_key',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: 'IDENTITY',
        comment: '엔티티 식별자',
      },
      {
        id: 'column-entities-snapshot-key',
        isPK: false,
        isFK: false,
        logicalName: '스냅샷 키',
        physicalName: 'snapshot_key',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '연결된 스냅샷',
      },
      {
        id: 'column-entities-name',
        isPK: false,
        isFK: false,
        logicalName: '엔티티명',
        physicalName: 'name',
        dataType: 'VARCHAR(255)',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: 'ERD 엔티티 이름',
      },
    ],
  },
  {
    id: 'table-entity-columns',
    name: 'entity_columns',
    identifier: 'entity_columns',
    x: 520,
    y: 320,
    color: 'user4',
    columns: [
      {
        id: 'column-entity-columns-key',
        isPK: true,
        isFK: false,
        logicalName: '컬럼 키',
        physicalName: 'entity_column_key',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: 'IDENTITY',
        comment: '엔티티 컬럼 식별자',
      },
      {
        id: 'column-entity-columns-entity-key',
        isPK: false,
        isFK: false,
        logicalName: '엔티티 키',
        physicalName: 'entity_key',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '연결된 엔티티',
      },
      {
        id: 'column-entity-columns-name',
        isPK: false,
        isFK: false,
        logicalName: '컬럼명',
        physicalName: 'column_name',
        dataType: 'VARCHAR(255)',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '필드 명칭',
      },
      {
        id: 'column-entity-columns-type',
        isPK: false,
        isFK: false,
        logicalName: '데이터 타입',
        physicalName: 'data_type',
        dataType: 'VARCHAR(100)',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '데이터 타입',
      },
    ],
  },
];

type ImportResultState = {
  type: 'error';
  correctedSql: string;
  changeSummary: string[];
  tables: WorkspaceTable[];
};

const cloneTables = (tables: WorkspaceTable[]): WorkspaceTable[] =>
  tables.map((table) => ({
    ...table,
    columns: table.columns.map((column) => ({ ...column })),
  }));

interface WorkspaceLayoutProps {
  mode?: WorkspaceMode;
}

const WorkspaceLayout: React.FC<WorkspaceLayoutProps> = ({ mode = 'edit' }) => {
  const {
    projectKey,
    activeTool,
    setActiveTool,
    replaceTables,
    updateTablePosition,
    addTableFromWebSocket,
    updateTableFromWebSocket,
    removeTableFromWebSocket,
    addColumnFromWebSocket,
    updateColumnFromWebSocket,
    updateColumnByKeyFromWebSocket,
    removeColumnFromWebSocket,
    addRelationFromWebSocket,
    removeRelationFromWebSocket,
    setTableLockState,
    // handleAiDraftConfirm,
    handleAiDraftCancel,
  } = useWorkspace();
  const isViewMode = mode === 'view';
  const [sqlPreview, setSqlPreview] = useState('');
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [isCopying, setIsCopying] = useState(false);
  const [showCopyToast, setShowCopyToast] = useState(false);
  const [isImportProcessing, setIsImportProcessing] = useState(false);
  const [importResult, setImportResult] = useState<ImportResultState | null>(
    null,
  );
  const [isImportResultOpen, setIsImportResultOpen] = useState(false);
  const [isImportRetryOpen, setIsImportRetryOpen] = useState(false);

  // URL에서 projectKey 가져오기
  const params = useParams<{ projectKey: string; viewId: string }>();

  const setProjectKey = useAuthStore((state) => state.setProjectKey);

  // AI Draft Store
  const aiDraftResult = useAiDraftStore((state) => state.aiDraftResult);
  const aiPreviewTables = useAiDraftStore((state) => state.previewTables);

  // AI Draft 모달 상태 (aiDraftResult가 있으면 모달 표시)
  const isAiDraftConfirmOpen = !!aiDraftResult;

  // WebSocket 관련 상태
  const wsClientRef = useRef<ErdWebSocketClient | null>(null);
  const currentUser = useAuthStore((state) => state.currentUser);

  // 원격 커서 상태 (다른 사용자들의 커서)
  const [remoteCursors, setRemoteCursors] = useState<
    Record<string, RemoteCursorType>
  >({});

  const viewerLinkKey = params.viewId;

  useViewerStream(isViewMode, viewerLinkKey);

  // projectKey를 authStore에 저장
  useEffect(() => {
    if (params.projectKey) {
      const projectKeyNum = parseInt(params.projectKey, 10);
      if (!isNaN(projectKeyNum)) {
        setProjectKey(projectKeyNum);
      }
    }
  }, [params.projectKey, setProjectKey]);

  // WebSocket 초기화
  useEffect(() => {
    if (isViewMode) return; // 뷰어 모드에서는 WebSocket 사용 안 함

    // authStore에서 실제 값 가져오기
    const projectKey = useAuthStore.getState().projectKey;

    // projectKey가 없으면 연결하지 않음
    if (!projectKey) {
      console.warn('⚠️ No projectKey found, skipping WebSocket connection');
      return;
    }

    console.log('🔌 Initializing WebSocket...');
    console.log('Project Key:', projectKey);
    console.log('User:', currentUser);

    // accessToken은 임시로 빈 문자열 (쿠키로 인증 처리)
    const wsClient = new ErdWebSocketClient({
      projectKey,
      accessToken: '',
    });

    // 이벤트 핸들러 등록
    wsClient.setEventHandlers({
      onTableMove: (event) => {
        console.log('📥 Received TABLE_MOVE:', event);
        const tableEvent = event.event as {
          tableKey: number;
          xPosition: number;
          yPosition: number;
        };

        // 자기 이벤트는 무시 (이미 로컬 업데이트 완료)
        if (event.userKey === currentUser?.userKey) {
          return;
        }

        // 다른 사용자의 테이블 이동 → 화면 업데이트
        updateTablePosition(`table-${tableEvent.tableKey}`, {
          x: tableEvent.xPosition,
          y: tableEvent.yPosition,
        });
      },
      onCursorMove: (event) => {
        console.log('📥 Received CURSOR_MOVE:', event);
        const cursorEvent = event.event as {
          userEmail?: string;
          userName?: string;
          userColor?: string;
          xPosition: number;
          yPosition: number;
        };

        // 자기 커서는 무시
        if (event.userKey === currentUser?.userKey) {
          return;
        }

        // 다른 사용자의 커서 업데이트
        const userEmail = cursorEvent.userEmail || `user-${event.userKey}`;
        setRemoteCursors((prev) => ({
          ...prev,
          [userEmail]: {
            userEmail,
            userName: cursorEvent.userName || '익명',
            userColor: cursorEvent.userColor || '#3b82f6',
            xPosition: cursorEvent.xPosition,
            yPosition: cursorEvent.yPosition,
          },
        }));
      },
      onTableLock: (event) => {
        console.log('📥 Received TABLE_LOCK:', event);
        const lockEvent = event.event as {
          tableKey: number;
          userEmail?: string;
          userName?: string;
        };

        // 락 이벤트 처리 (자기 자신 포함)
        if (lockEvent.userEmail && lockEvent.userName) {
          // 자기 자신의 락인 경우
          if (event.userKey === currentUser?.userKey) {
            console.log(`✅ 내가 락을 획득했습니다: ${lockEvent.tableKey}`);
            // 자기 자신의 락은 로컬 상태만 업데이트 (다른 사용자에게는 잠김 표시 안 함)
            return;
          }

          // 다른 사용자가 락을 획득한 경우
          setTableLockState(`table-${lockEvent.tableKey}`, true, {
            userEmail: lockEvent.userEmail,
            userName: lockEvent.userName,
          });
          console.log(
            `🔒 테이블이 잠겼습니다: ${lockEvent.tableKey} by ${lockEvent.userName}`,
          );
        }
      },
      onTableUnlock: (event) => {
        console.log('📥 Received TABLE_UNLOCK:', event);
        const unlockEvent = event.event as {
          tableKey: number;
          userEmail?: string;
        };

        // 자기 이벤트는 무시
        if (event.userKey === currentUser?.userKey) {
          return;
        }

        // 다른 사용자가 락을 해제한 경우
        setTableLockState(`table-${unlockEvent.tableKey}`, false);
        console.log(`🔓 테이블 잠금이 해제되었습니다: ${unlockEvent.tableKey}`);
      },
      onColumnCreate: (event) => {
        console.log('📥 Received COLUMN_NEW:', event);

        const columnData = event.event as unknown as {
          columnKey: number;
          tableKey: number;
          logicalName: string;
          physicalName: string;
          dataType: string;
          dataDetail: string[] | null;
          isNullable: boolean;
          isPrimaryKey: boolean;
          isForeignKey: boolean;
          isUnique: boolean;
          isIncremental: boolean;
          defaultValue: string | null;
          comment: string;
          columnOrder: number;
        };

        const newColumn = {
          id: `column-${columnData.columnKey}`,
          key: columnData.columnKey,
          isPK: columnData.isPrimaryKey,
          isFK: columnData.isForeignKey,
          logicalName: columnData.logicalName || 'Logical Name',
          physicalName: columnData.physicalName || 'Physical Name',
          domain: '',
          dataType: columnData.dataType || 'VARCHAR',
          allowNull: columnData.isNullable ? 'Y' : 'N',
          defaultValue: columnData.defaultValue || 'Default Value',
          comment: columnData.comment || 'Comment',
        };

        // 내가 생성한 컬럼이면 key만 업데이트 (updateColumnFromWebSocket이 임시 컬럼을 찾아서 업데이트)
        if (event.userKey === currentUser?.userKey) {
          updateColumnFromWebSocket(columnData.tableKey, newColumn);
          console.log('🔄 내가 생성한 컬럼에 key 업데이트:', newColumn.key);
          return;
        }

        // 다른 사용자가 생성한 컬럼은 새로 추가
        addColumnFromWebSocket(columnData.tableKey, newColumn);
        console.log('🔄 다른 사용자가 컬럼을 생성했습니다:', newColumn);
      },
      onColumnUpdate: (event) => {
        console.log('📥 Received COLUMN_UPDATED:', event);
        // 자기 이벤트는 무시
        if (event.userKey === currentUser?.userKey) {
          return;
        }

        const columnData = event.event as unknown as {
          columnKey: number;
          tableKey?: number;
          logicalName: string;
          physicalName: string;
          dataType: string;
          dataDetail: string[] | null;
          isNullable: boolean;
          isPrimaryKey: boolean;
          isForeignKey: boolean;
          isUnique: boolean;
          isIncremental: boolean;
          defaultValue: string | null;
          comment: string;
          columnOrder: number;
        };

        // tableKey를 찾아야 함 (columnKey로 테이블 찾기)
        // 백엔드에서 tableKey를 보내주지 않으면 모든 테이블에서 찾아야 함
        const updatedColumn = {
          id: `column-${columnData.columnKey}`,
          key: columnData.columnKey,
          isPK: columnData.isPrimaryKey,
          isFK: columnData.isForeignKey,
          logicalName: columnData.logicalName || '',
          physicalName: columnData.physicalName || '',
          domain: '',
          dataType: columnData.dataType || 'VARCHAR',
          allowNull: columnData.isNullable ? 'Y' : 'N',
          defaultValue: columnData.defaultValue || '',
          comment: columnData.comment || '',
        };
        // columnKey로 모든 테이블에서 찾아서 업데이트
        updateColumnByKeyFromWebSocket(updatedColumn);
        // // tableKey가 있으면 해당 테이블에서 업데이트
        // if (columnData.tableKey) {
        //   updateColumnFromWebSocket(columnData.tableKey, updatedColumn);
        // } else {
        //   // tableKey가 없으면 columnKey로 모든 테이블에서 찾아서 업데이트
        //   // 이 경우 모든 테이블을 순회해야 하므로 비효율적
        //   // 임시로 첫 번째 테이블에서 시도
        //   console.warn('tableKey가 없어서 컬럼 업데이트를 시도합니다.');
        // }

        console.log('🔄 다른 사용자가 컬럼을 수정했습니다:', updatedColumn);
      },
      onColumnDelete: (event) => {
        console.log('📥 Received COLUMN_DELETE:', event);
        // 자기 이벤트는 무시
        if (event.userKey === currentUser?.userKey) {
          return;
        }

        const columnData = event.event as unknown as {
          columnKey: number;
        };

        if (columnData.columnKey) {
          removeColumnFromWebSocket(columnData.columnKey);
          console.log(
            '🔄 다른 사용자가 컬럼을 삭제했습니다:',
            columnData.columnKey,
          );
        }
      },
      onTableCreate: (event) => {
        console.log('📥 Received TABLE_NEW:', event);

        // 백엔드에서 받은 테이블 데이터
        const tableData = event.event as unknown as {
          tableKey: number;
          projectKey: number;
          logicalName: string;
          physicalName: string;
          colorHex: string;
          xposition: number;
          yposition: number;
          createdAt: string;
          updatedAt: string;
        };

        // colorHex를 WorkspaceTableColor로 변환
        const getColorFromHex = (hex: string): WorkspaceTableColor => {
          const normalizedHex = hex.toUpperCase();
          const TABLE_COLOR_HEX_MAP: Record<WorkspaceTableColor, string> = {
            blue: '#1E50AF',
            user2: '#5271C4',
            user3: '#70B2FF',
            user4: '#44C2B3',
            user5: '#A3E0A9',
            user6: '#FFD166',
            user7: '#FF9F5A',
            user8: '#C18AFF',
          };
          const colorEntry = Object.entries(TABLE_COLOR_HEX_MAP).find(
            ([, value]) =>
              value.replace('#', '').toUpperCase() === normalizedHex,
          );
          return (colorEntry?.[0] as WorkspaceTableColor) || 'blue';
        };

        // 새 테이블 생성
        const newTable: WorkspaceTable = {
          id: `table-${tableData.tableKey}`,
          key: tableData.tableKey,
          name: tableData.logicalName,
          identifier: tableData.physicalName,
          x: tableData.xposition,
          y: tableData.yposition,
          color: getColorFromHex(tableData.colorHex),
          columns: [],
        };

        const isSelfEvent = event.userKey === currentUser?.userKey;

        if (isSelfEvent) {
          // 내가 생성한 테이블: 기존 임시 테이블을 업데이트
          updateTableFromWebSocket(newTable);
          console.log(
            '✅ 내가 생성한 테이블이 백엔드에서 확정되었습니다:',
            newTable,
          );
        } else {
          // 다른 사용자가 생성한 테이블: 새로 추가
          addTableFromWebSocket(newTable);
          console.log('🔄 다른 사용자가 테이블을 생성했습니다:', newTable);
        }
      },
      onTableUpdate: (event) => {
        console.log('📥 Received TABLE_UPDATE:', event);
        // 자기 이벤트는 무시
        if (event.userKey === currentUser?.userKey) {
          return;
        }
        // TODO: 테이블 업데이트 로직 구현
        console.log('🔄 다른 사용자가 테이블을 수정했습니다.');
      },
      onTableDelete: (event) => {
        console.log('📥 Received TABLE_DELETE:', event);
        // 자기 이벤트는 무시
        if (event.userKey === currentUser?.userKey) {
          return;
        }

        // 삭제된 테이블 키 추출
        const tableData = event.event as unknown as {
          tableKey: number;
        };

        if (tableData.tableKey) {
          removeTableFromWebSocket(tableData.tableKey);
          console.log(
            '🔄 다른 사용자가 테이블을 삭제했습니다:',
            tableData.tableKey,
          );
        }
      },
      onRelationCreate: (event) => {
        console.log('📥 Received RELATION_NEW:', event);

        const relationData = event.event as unknown as {
          relationKey: number;
          projectKey: number;
          fromTableKey: number;
          fromColumnKey: number;
          toTableKey: number;
          toColumnKey: number;
          relationType: string;
          constraintName: string;
          onDeleteAction: string;
          onUpdateAction: string;
        };

        // relationType을 cardinality로 변환
        const cardinalityMap: Record<
          string,
          '1' | '11' | '13' | '01' | '01-1' | '013'
        > = {
          STRICT_ONE_TO_ONE: '11',
          STRICT_ONE_TO_MANY: '13',
          OPTIONAL_ONE_TO_ONE: '01',
          OPTIONAL_ONE_TO_MANY: '013',
        };

        // constraintName으로 type 결정
        const type: RelationType =
          relationData.constraintName === '식별'
            ? 'identifying'
            : 'non-identifying';

        const newRelation: WorkspaceRelation = {
          id: `relation-${relationData.relationKey}`,
          sourceTableId: `table-${relationData.fromTableKey}`,
          targetTableId: `table-${relationData.toTableKey}`,
          type,
          cardinality: cardinalityMap[relationData.relationType] || '13',
        };

        // 내가 생성한 관계선이면 무시 (이미 로컬에서 추가됨)
        if (event.userKey === currentUser?.userKey) {
          console.log('🔄 내가 생성한 관계선입니다:', newRelation);
          return;
        }

        // 다른 사용자가 생성한 관계선은 새로 추가
        addRelationFromWebSocket(newRelation);
        console.log('🔄 다른 사용자가 관계선을 생성했습니다:', newRelation);
      },
      onRelationDelete: (event) => {
        console.log('📥 Received RELATION_DELETE:', event);
        // 자기 이벤트는 무시
        if (event.userKey === currentUser?.userKey) {
          return;
        }

        const relationData = event.event as unknown as {
          relationKey: number;
        };

        if (relationData.relationKey) {
          removeRelationFromWebSocket(relationData.relationKey);
          console.log(
            '🔄 다른 사용자가 관계선을 삭제했습니다:',
            relationData.relationKey,
          );
        }
      },
    });

    wsClientRef.current = wsClient;

    // 자동으로 연결 시작
    wsClient.connect();

    return () => {
      console.log('🔌 Cleaning up WebSocket...');
      wsClient.disconnect();
    };
  }, [
    isViewMode,
    currentUser,
    updateTablePosition,
    addTableFromWebSocket,
    updateTableFromWebSocket,
    removeTableFromWebSocket,
    addColumnFromWebSocket,
    updateColumnFromWebSocket,
    updateColumnByKeyFromWebSocket,
    removeColumnFromWebSocket,
    addRelationFromWebSocket,
    removeRelationFromWebSocket,
    setTableLockState,
  ]);

  const handleCloseImportModal = useCallback(() => {
    setActiveTool('cursor');
    setIsImportProcessing(false);
  }, [setActiveTool]);

  const handleImportSubmit = useCallback(
    (ddl: string) => {
      setIsImportProcessing(true);
      window.setTimeout(() => {
        const trimmed = ddl.trim();
        const hasCreateTable = /create\s+table/i.test(trimmed);
        const forceError = /force_error/i.test(trimmed);
        const isValid = trimmed.length > 0 && hasCreateTable && !forceError;

        if (isValid) {
          replaceTables(cloneTables(IMPORT_CORRECTED_TABLES));
          setImportResult(null);
          setIsImportResultOpen(false);
        } else {
          setImportResult({
            type: 'error',
            correctedSql: IMPORT_ERROR_SQL,
            changeSummary: IMPORT_ERROR_CHANGE_SUMMARY,
            tables: cloneTables(IMPORT_CORRECTED_TABLES),
          });
          setIsImportResultOpen(true);
        }

        setIsImportProcessing(false);
        handleCloseImportModal();
      }, 600);
    },
    [handleCloseImportModal, replaceTables],
  );

  const handleImportResultConfirm = useCallback(() => {
    if (importResult?.tables) {
      replaceTables(cloneTables(importResult.tables));
    }
    setImportResult(null);
    setIsImportResultOpen(false);
  }, [importResult, replaceTables]);

  const handleImportResultClose = useCallback(() => {
    setImportResult(null);
    setIsImportResultOpen(false);
    setIsImportRetryOpen(true);
  }, []);

  const handleImportRetryConfirm = useCallback(() => {
    setIsImportRetryOpen(false);
    setActiveTool('import');
    setIsImportProcessing(false);
  }, [setActiveTool]);

  const handleCloseExportModal = useCallback(() => {
    setActiveTool('cursor');
    setSqlPreview('');
    setIsPreviewLoading(false);
    setIsCopying(false);
    setShowCopyToast(false);
  }, [setActiveTool]);

  const handlePreviewClick = useCallback(
    async (database: ExportDatabase) => {
      if (!projectKey) {
        console.error('projectKey가 없습니다.');
        return;
      }

      setIsPreviewLoading(true);

      // ExportDatabase를 SqlDialect로 변환
      const dialectMap: Record<ExportDatabase, SqlDialect> = {
        mysql: 'MYSQL',
        postgresql: 'POSTGRESQL',
      };
      const dialect = dialectMap[database];

      try {
        const sql = await exportErdToSql(projectKey, dialect);
        setSqlPreview(sql);
      } catch (error) {
        console.error('SQL Export 실패:', error);
        // 에러 시 더미 데이터 표시
        setSqlPreview(dummySqlPreview[database]);
      } finally {
        setIsPreviewLoading(false);
      }
    },
    [projectKey],
  );

  const handleCopyClick = useCallback(
    async (database: ExportDatabase) => {
      const textToCopy =
        sqlPreview && sqlPreview.trim().length > 0
          ? sqlPreview
          : dummySqlPreview[database];

      if (!textToCopy) {
        return;
      }

      if (!sqlPreview || sqlPreview.trim().length === 0) {
        setSqlPreview(dummySqlPreview[database]);
      }

      setIsCopying(true);
      try {
        if (
          navigator.clipboard &&
          typeof navigator.clipboard.writeText === 'function'
        ) {
          await navigator.clipboard.writeText(textToCopy);
        } else {
          const textarea = document.createElement('textarea');
          textarea.value = textToCopy;
          textarea.style.position = 'fixed';
          textarea.style.opacity = '0';
          document.body.appendChild(textarea);
          textarea.focus();
          textarea.select();
          document.execCommand('copy');
          document.body.removeChild(textarea);
        }
        setShowCopyToast(true);
      } catch (error) {
        console.error('SQL 복사에 실패했습니다.', error);
      } finally {
        setIsCopying(false);
      }
    },
    [sqlPreview],
  );

  useEffect(() => {
    if (!showCopyToast) {
      return;
    }

    const timer = window.setTimeout(() => {
      setShowCopyToast(false);
    }, 2000);

    return () => window.clearTimeout(timer);
  }, [showCopyToast]);

  const isImportModalOpen = activeTool === 'import';
  const isExportModalOpen = activeTool === 'export';

  return (
    <>
      <div className="flex w-full flex-col">
        <div className="flex h-[calc(100vh-70px)] min-h-[calc(100vh-70px)] overflow-hidden bg-my-white">
          {/* 뷰어 모드에서는 왼쪽 사이드바 숨김 */}
          {!isViewMode && <LeftSideBar />}
          <div className="flex min-h-0 flex-1 overflow-hidden">
            <WorkspaceCanvas
              mode={mode}
              wsClient={wsClientRef.current}
              currentUserKey={currentUser?.userKey}
            />
          </div>
          {/* 뷰어 모드에서는 오른쪽 사이드바 숨김 */}
          {!isViewMode && <RightSideBar />}
        </div>
      </div>

      {/* 뷰어 모드에서는 Import/Export 모달 숨김 */}
      {!isViewMode && (
        <>
          <ImportModal
            isOpen={isImportModalOpen}
            onClose={handleCloseImportModal}
            onSubmit={handleImportSubmit}
            isProcessing={isImportProcessing}
          />
          <ExportModal
            isOpen={isExportModalOpen}
            onClose={handleCloseExportModal}
            sqlPreview={sqlPreview}
            onClickPreview={handlePreviewClick}
            onClickDownload={handleCopyClick}
            isPreviewLoading={isPreviewLoading}
            isDownloadLoading={isCopying}
          />
          {importResult && (
            <ImportResultModal
              isOpen={isImportResultOpen}
              onClose={handleImportResultClose}
              onConfirm={handleImportResultConfirm}
              type={importResult.type}
              correctedSql={importResult.correctedSql}
              changeSummary={importResult.changeSummary}
            />
          )}
          <ImportRetryModal
            isOpen={isImportRetryOpen}
            message="SQL문을 다시 입력하시기 바랍니다."
            onConfirm={handleImportRetryConfirm}
          />
        </>
      )}
      {showCopyToast && (
        <div className="fixed bottom-6 left-1/2 z-50">
          <div className="-translate-x-1/2 transform">
            <div className="flex items-center gap-2 rounded-[10px] bg-my-black px-6 py-3 text-my-white shadow-lg animate-fadeIn">
              <BuildSuccessIcon className="h-5 w-5" />
              <span className="font-pretendard text-sm font-medium">
                SQL이 복사되었습니다.
              </span>
            </div>
          </div>
        </div>
      )}


      {/* 원격 커서들 렌더링 */}
      {!isViewMode &&
        Object.values(remoteCursors).map((cursor) => (
          <RemoteCursor
            key={cursor.userEmail}
            userName={cursor.userName}
            userColor={cursor.userColor}
            xPosition={cursor.xPosition}
            yPosition={cursor.yPosition}
          />
        ))}

      {/* AI 초안 컨펌 배너 */}
      {!isViewMode && (
        <AiDraftConfirmBanner
          isOpen={isAiDraftConfirmOpen}
          // onConfirm={handleAiDraftConfirm}
          onConfirm={() => console.log("아직 구현되지 않았음.")}
          onCancel={handleAiDraftCancel}
          tableCount={aiPreviewTables.length}
          explanation={aiDraftResult?.explanation}
        />
      )}
    </>
  );
};

interface WorkSpacePageProps {
  mode?: WorkspaceMode;
  projectKeyFromViewCode?: number;
}

const WorkSpacePage: React.FC<WorkSpacePageProps> = ({
  mode = 'edit',
  projectKeyFromViewCode,
}) => {
  const params = useParams<{ projectKey: string; viewId: string }>();

  // [핵심 로직] projectKey 결정:
  // 1. /project/:projectKey/workspace 라우트일 경우: params.projectKey 사용
  // 2. /viewer/:viewId 라우트일 경우: undefined
  //    (이후 WorkspaceProvider가 viewId를 이용해 서버에서 projectKey를 찾아야 함)
  const keyFromUrl = params.projectKey
    ? parseInt(params.projectKey, 10)
    : projectKeyFromViewCode;
  // const viewIdFromUrl = params.viewId;

  // URL에서 가져온 projectKey를 Provider에게 prop으로 전달합니다.
  // 이 Prop이 WorkspaceProvider의 초기 데이터 로드에 사용됩니다.
  return (
    <WorkspaceProvider
      mode={mode}
      initialProjectKey={keyFromUrl} // [수정] Prop으로 key 전달
      // viewId={viewIdFromUrl}       // [추가] 뷰어 모드일 때 viewId 전달
    >
      <WorkspaceLayout mode={mode} />
    </WorkspaceProvider>
  );
};

export default WorkSpacePage;
